/* SPDX-License-Identifier: GPL-2.0-or-later. Unified client-side workspace editors. */
(function(host){
'use strict';
function create(ctx){
 const {A,state}=ctx,M=host.DDNWorkbenchModel,$=id=>document.getElementById(id);
 let cached=null,revision=-1,workspace=null,active=null,tabs=[],lastView=null,pendingScroll=null;
 const sessions=new Map(),drafts=new Map();let panelRevision=0,editorRefresh=false;
 const element=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const run=fn=>ctx.guard(fn);
 const button=(text,fn,parent,edit=false)=>{const b=element('button',text);b.type='button';b.disabled=edit&&!state.config.design;if(edit)b.dataset.workspaceEdit='';b.addEventListener('click',()=>run(fn));parent?.append(b);return b;};
 const files=()=>state.ws?.getFiles()||{};
 function index(){if(!cached||workspace!==state.ws||revision!==state.ws?.revision){workspace=state.ws;revision=state.ws?.revision;cached=M.index(files(),A);}return cached;}
 const top=element('div',undefined,'ddn-workspace-bar');top.id='ddn-workspace-bar';
 const name=element('strong','Workspace');name.id='ddn-workspace-name';top.append(name);
 for(const [label,id]of [['New','ddn-new-project'],['Open','ddn-open'],['Save','ddn-creator-save'],['Save As','ddn-creator-saveas'],['Undo','ddn-undo'],['Redo','ddn-redo']]){const b=button(label,()=>$ (id).click(),top,['New','Save','Save As','Undo','Redo'].includes(label));b.dataset.command=id;}
 const saved=element('span','', 'ddn-dim');saved.id='ddn-workspace-dirty';top.append(saved);$('ddn-toolbar').after(top);
 const nav=element('section');nav.id='ddn-workspace-nav';const navhead=element('div',undefined,'ddn-row');nav.append(navhead);
 const mode=element('select');mode.setAttribute('aria-label','Workspace navigator mode');for(const v of ['Logical','Files'])mode.add(new Option(v,v));navhead.append(mode);
 const search=element('input');search.type='search';search.placeholder='Find sections or definitions';search.setAttribute('aria-label','Search workspace');nav.append(search);
 const tree=element('div');tree.id='ddn-workspace-tree';nav.append(tree);const fileBody=$('ddn-drawer-files').querySelector('.ddn-drawer-body');fileBody.prepend(nav);
 const legacy=element('details');legacy.id='ddn-workspace-file-actions';legacy.append(element('summary','Open, import, files and downloads'));for(const child of [...fileBody.children])if(child!==nav)legacy.append(child);fileBody.append(legacy);
 $('ddn-drawer-files').querySelector('h2').textContent='Workspace';$('ddn-icon-files').title='Workspace — models, views, shared settings, text and automation';
 const tabbar=element('div');tabbar.id='ddn-workspace-tabs';tabbar.setAttribute('role','tablist');tabbar.setAttribute('aria-label','Open workspace editors');$('ddn-center').prepend(tabbar);
 const scope=element('div');scope.id='ddn-edit-scope';tabbar.after(scope);
 const panel=element('section');panel.id='ddn-workspace-editor';panel.hidden=true;scope.after(panel);
 const footer=element('div',undefined,'ddn-workspace-footer');$('ddn-center').append(footer);
 for(const title of ['Problems','Changes','Source'])button(title,()=>title==='Source'?ctx.openSource(state.currentFile||state.entry):openSpecial(title.toLowerCase()),footer);
 button('View contents',()=>openSpecial('contents'),footer);button('View settings',()=>ctx.drawer('document'),footer);button('Publish',()=>openSpecial('publication'),footer);
 function viewItem(){return index()?.views.find(v=>v.file===state.entry&&(v.view===state.view||v.uid===state.view||v.node.id===state.view));}
 function title(t){const item=t.item&&index().byKey.get(t.item);if(!item)return t.label;return item.label+(t.type==='view'&&index().views.filter(v=>v.label===item.label).length>1?' · '+item.module:'');}
 function rememberTab(t){if(!tabs.some(x=>x.key===t.key))tabs.push(t);renderTabs();}
 function renderTabs(){tabbar.replaceChildren();for(const t of tabs){const wrap=element('span',undefined,'ddn-workspace-tab');const b=button(title(t)+(drafts.has(t.key)?' •':''),()=>activate(t),wrap);b.setAttribute('role','tab');b.setAttribute('aria-selected',String(active?.key===t.key));b.title=t.file||t.key;b.dataset.tabKey=t.key;const close=button('×',()=>closeTab(t),wrap);close.setAttribute('aria-label','Close '+title(t));tabbar.append(wrap);}button('+ View',()=>viewForm(),tabbar,true);}
 tabbar.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||e.target.getAttribute('role')!=='tab')return;const bs=[...tabbar.querySelectorAll('[role=tab]')],at=bs.indexOf(e.target),next=e.key==='Home'?0:e.key==='End'?bs.length-1:(at+(e.key==='ArrowRight'?1:-1)+bs.length)%bs.length;e.preventDefault();bs[next].click();bs[next].focus();});
 function closeTab(t){if(drafts.has(t.key)&&!confirm('Discard the unapplied changes in '+title(t)+'?'))return;drafts.delete(t.key);tabs=tabs.filter(x=>x.key!==t.key);if(active?.key===t.key){const next=tabs.at(-1);if(next)activate(next);else{active=null;panel.hidden=true;$('ddn-stage').hidden=false;}}renderTabs();}
 function setPanel(t){active=t;rememberTab(t);panel.hidden=false;$('ddn-stage').hidden=true;panel.replaceChildren();panelRevision=drafts.get(t.key)?.revision??state.ws.revision;const heading=element('div',undefined,'ddn-workspace-heading');heading.append(element('h2',title(t)));button('Back to diagram',()=>{const v=viewItem();if(v)openView(v);},heading);panel.append(heading);const status=element('p','Changes apply to the workspace in memory. Save writes the complete workspace.','ddn-dim');panel.append(status);setScope(t.item?index().byKey.get(t.item):null);}
 function field(parent,label,value='',options){const l=element('label',undefined,'ddn-field');l.append(element('span',label));let e;if(Array.isArray(options)){e=element('select');for(const o of options)e.add(new Option(typeof o==='string'?o:o.label,typeof o==='string'?o:o.value));}else e=element(options==='text'?'textarea':'input');e.value=value??'';e.setAttribute('aria-label',label);if(options==='text'){e.rows=12;e.spellcheck=false;}l.append(e);parent.append(l);
 const old=drafts.get(active?.key)?.values?.[label];if(old!==undefined)e.value=old;
 e.addEventListener('input',()=>{const d=drafts.get(active.key)||{revision:panelRevision,values:{}};d.values[label]=e.value;drafts.set(active.key,d);renderTabs();});return e;}
 function check(parent,label,value){const e=field(parent,label,'');e.type='checkbox';e.checked=drafts.get(active.key)?.values?.[label]??value;e.addEventListener('change',()=>{const d=drafts.get(active.key)||{revision:panelRevision,values:{}};d.values[label]=e.checked;drafts.set(active.key,d);renderTabs();});return e;}
 function setScope(item){scope.replaceChildren();const v=viewItem();scope.append(element('span','View: '+(v?v.label+' · '+v.file:'none')));if(item){scope.append(element('strong','Editing '+item.type+': '+item.module+'::'+item.path+' · '+item.file));const uses=M.users(index(),item);if(uses.length)scope.append(element('span','Referenced by '+uses.length+' declaration(s)'));}}
 function selection(){if(active?.type!=='view')return;const id=state.selected||state.selectedRelation;if(!id){setScope(null);return;}let model=id;try{model=ctx.sourceIdentity(id);}catch{}const item=index().items.find(x=>x.uid===model);setScope(item);if(item)scope.append(element('span','Definition is shared · appearance belongs to '+state.view));}
 function refresh(){if(!state.ws)return;index();tabs=tabs.filter(t=>!t.item||index().byKey.has(t.item)||drafts.has(t.key));top.hidden=!state.config.design;tabbar.hidden=!state.config.toolbar||!state.config.icons;scope.hidden=tabbar.hidden;footer.hidden=tabbar.hidden;name.textContent=(state.entry||'Workspace').split('/').at(-1);saved.textContent=ctx.dirty()?'Unsaved workspace':'Saved workspace';
 for(const b of document.querySelectorAll('[data-workspace-edit]'))b.disabled=!state.config.design;
 for(const b of top.querySelectorAll('[data-command]')){const original=$(b.dataset.command);b.disabled=original.disabled||(!state.config.design&&b.dataset.command!=='ddn-open');}
 renderNav();renderTabs();selection();if(active&&active.type!=='view'&&panelRevision!==state.ws.revision&&!drafts.has(active.key)&&!editorRefresh){editorRefresh=true;queueMicrotask(()=>{editorRefresh=false;if(active&&active.type!=='view'&&!drafts.has(active.key))run(()=>activate(active));});}}
 function navButton(item,parent){const b=button(item.label,()=>item.type==='view'?openView(item):openItem(item),parent);b.title=item.file+' / '+item.module+'::'+item.path;b.dataset.workspaceKey=item.key;return b;}
 function renderNav(){const idx=index();if(!idx)return;tree.replaceChildren();const query=search.value.trim().toLowerCase();const match=x=>!query||(x.file+' '+x.module+' '+x.path+' '+x.label).toLowerCase().includes(query);
 const group=(label,items,action)=>{const d=element('details');d.open=true;const summary=element('summary',label+' ('+items.length+')');d.append(summary);if(action)button('Manage '+label,action,d);for(const item of items.filter(match)){const row=element('div',undefined,'ddn-workspace-nav-row');navButton(item,row);d.append(row);}tree.append(d);};
 if(mode.value==='Files'){for(const [file]of Object.entries(idx.files)){const d=element('details');d.open=!!query;d.append(element('summary',file));button('Open source',()=>ctx.openSource(file),d);for(const item of idx.items.filter(x=>x.file===file&&!x.group&&match(x)))navButton(item,d);if(file.endsWith('.ddnn'))button('Open documents',()=>openSpecial('documents'),d);tree.append(d);}}
 else{
 group('Models',idx.items.filter(x=>['data','object','relation','domain','sample','flow','assertion','fragment','fields','ports'].includes(x.type)&&!x.group&&!ctx.isCompanion(x.file,files()[x.file])),()=>openSpecial('models'));
 group('Views',idx.views,()=>openSpecial('views'));
 group('Shared settings',idx.items.filter(x=>x.type==='format'||x.parent&&idx.byKey.get(x.parent)?.type==='format'),()=>openSpecial('settings'));
 group('Text documents',idx.documents.map(d=>({...d,label:d.id,module:'',path:d.id,type:'text-document'})),()=>openSpecial('documents'));
 group('Automation',idx.items.filter(x=>x.type==='architecture'||x.node.props?.x_profile||x.node.props?.x_keel||x.node.props?.x_trace),()=>openSpecial('automation'));
 }
 for(const {file,error}of idx.errors)button(file+' — '+error.message,()=>ctx.openSource(file),tree);
 }
 mode.addEventListener('change',renderNav);search.addEventListener('input',renderNav);
 function openView(item){const v=M.find(index(),item);active={key:'view:'+v.key,type:'view',item:v.key,label:v.label,file:v.file};rememberTab(active);panel.hidden=true;$('ddn-stage').hidden=false;state.entry=v.file;state.view=v.view;ctx.entries(v.view);ctx.mount();setScope(null);}
 function activate(t){if(t.type==='rules'){openRules(t.file);return;}if(t.type==='view'){const v=index().byKey.get(t.item);if(v)openView(v);else closeTab(t);return;}if(t.type==='item'){const item=index().byKey.get(t.item);if(item){if(t.key.startsWith('text:'))documentForElement(item);else openItem(item);}else closeTab(t);return;}if(t.type==='text-document'){openDocument(t.file,t.id);return;}if(t.type==='view-form'){viewForm(t.managed?index().byKey.get(t.managed):null);return;}openSpecial(t.type);}
 function openItem(item){if(item.type==='text-document'){openDocument(item.file,item.id);return;}setPanel({key:'item:'+item.key,type:'item',item:item.key,file:item.file,label:item.label});item=M.find(index(),item);panel.append(element('p',item.file+' → '+item.module+' → '+item.path,'ddn-dim'));const row=element('div',undefined,'ddn-row');panel.append(row);button('Show source',()=>ctx.openSource(item.file,item.node),row);button('Used by',()=>usage(item),row);
 const labelInput=field(panel,'Display name',item.node.label||item.node.id||'');if(item.node.id){const id=field(panel,'Identifier',item.node.id);button('Save name and identifier',()=>{let next=M.label(files(),item,labelInput.value,A);next=M.rename(next,item,id.value,A);commit(next,'Rename '+item.type);},panel,true);}
 if(item.type==='data'){dataEditor(item);return;}
 if(item.type==='object'){definitionEditor(item);return;}
 if(item.type==='view'){button('Open diagram',()=>openView(item),panel);button('Edit contents',()=>{openView(item);openSpecial('contents');},panel);}
 propertyEditor(item,panel);const children=index().items.filter(x=>x.parent===item.key);for(const child of children)navButton(child,panel);
 button('Delete '+item.type,()=>{if(confirm('Delete '+item.label+' from '+item.file+'? Referenced declarations cannot be deleted.'))commit(M.remove(files(),item,A),'Delete '+item.type);},panel,true);
 }
 function usage(item){const section=element('div');section.append(element('h3','Referenced by'));for(const u of M.users(index(),item))navButton(u,section);if(!section.querySelector('button'))section.append(element('p','No direct references.'));panel.append(section);}
 function jsonValue(value){return value===undefined?'':JSON.stringify(value);}
 function propertyEditor(item,parent){
 const box=element('fieldset');box.append(element('legend','Properties — '+item.file));parent.append(box);const controls=new Map();
 const enums={direction:['right','down','left','up'],note_wrap:['auto','on','off'],note_mode:['viewport','full']};
 for(const [k,v]of Object.entries(item.node.props||{})){
 let input,read;
 if(typeof v==='string'){input=field(box,k,v,enums[k]);read=()=>input.value===''?undefined:input.value;}
 else if(typeof v==='boolean'){input=field(box,k,String(v),['true','false','']);read=()=>input.value===''?undefined:input.value==='true';}
 else if(typeof v==='number'){input=field(box,k,v);input.type='number';input.step='any';read=()=>{if(!input.value.trim())return undefined;const n=Number(input.value);if(!Number.isFinite(n))throw Error(k+' must be a number');return n;};}
 else {input=field(box,k,jsonValue(v));read=()=>input.value.trim()?JSON.parse(input.value):undefined;}
 controls.set(k,read);
 }
 const advanced=element('details');advanced.append(element('summary','Advanced property'));box.append(advanced);
 const k=field(advanced,'New property',''),v=field(advanced,'New property value','');advanced.append(element('p','Use JSON values for structured properties and new properties. References: {"$ref":"name"}; lengths: {"$quantity":24,"unit":"px"}. Blank removes an override.','ddn-dim'));
 button('Apply properties',()=>{const values={};for(const [name,read]of controls)values[name]=read();if(k.value.trim())values[k.value.trim()]=JSON.parse(v.value);commit(M.props(files(),item,values,A),'Edit '+item.type);},box,true);
 if(['projection','notation','layout','style','display','publication','legend','chrome','validation','export','bundle'].includes(item.type))usage(item);
 }
 function dataEditor(item){const create=element('fieldset');create.append(element('legend','Create in '+item.file+' → '+item.path));panel.append(create);const id=field(create,'New definition ID','item'),caption=field(create,'New definition name','New element'),kind=field(create,'New definition kind','object',A.kinds.map(k=>({value:k.id,label:k.label+' ('+k.id+')'})));button('Create definition',()=>{M.identifier(id.value);const code='object '+id.value+' '+JSON.stringify(caption.value)+' {kind:'+JSON.stringify(kind.value)+';}';commit(M.append(files(),item,code,A),'Create definition');},create,true);
 const targets=index().items.filter(x=>x.type==='object'&&!ctx.isCompanion(x.file,files()[x.file]));if(targets.length){const rel=element('fieldset');rel.append(element('legend','Create relationship'));panel.append(rel);const rid=field(rel,'Relationship ID','relationship'),from=field(rel,'From definition',targets[0].key,targets.map(x=>({value:x.key,label:x.file+' / '+x.path}))),to=field(rel,'To definition',targets.at(-1).key,targets.map(x=>({value:x.key,label:x.file+' / '+x.path}))),verb=field(rel,'Relationship type',A.relations.find(x=>x.id==='assoc')?.id||A.relations[0].id,A.relations.map(x=>({value:x.id,label:x.label||x.id})));button('Create relationship',()=>{M.identifier(rid.value);let next=files();const f=M.ensureRef(next,item,from.value,A);next=f.files;const t=M.ensureRef(next,item,to.value,A);next=t.files;commit(M.append(next,item,'relation '+rid.value+' '+A.authoring.value(f.ref)+' -> '+A.authoring.value(t.ref)+' {verb:'+JSON.stringify(verb.value)+';}',A),'Create relationship');},rel,true);}
 const table=element('table',undefined,'ddn-data-table');const head=element('tr');for(const s of ['Definition','Type','Actions'])head.append(element('th',s));table.append(head);for(const n of index().items.filter(n=>n.parent===item.key)){const tr=element('tr');tr.append(element('td',n.label),element('td',n.node.props.kind||n.type));const td=element('td');navButton(n,td);if(n.type==='object')button('Add to active view',()=>addToView(n),td,true);tr.append(td);table.append(tr);}panel.append(table);
 }
 function definitionEditor(item){const kind=field(panel,'Element kind',item.node.props.kind||'object',A.kinds.map(k=>({value:k.id,label:k.label+' ('+k.id+')'})));button('Save kind',()=>commit(M.props(files(),item,{kind:kind.value},A),'Change kind'),panel,true);
 button('Add existing definition to active view',()=>addToView(item),panel,true);
 button('Show properties in diagram',()=>{const ir=state.ws.resolve(state.entry,state.view);if(!ir.elements.some(n=>n.id===item.uid))throw Error('Bind this model to the active view first');const v=viewItem();openView(v);ctx.select(item.uid);},panel);
 const fields=index().items.filter(x=>x.parent&&index().byKey.get(x.parent)?.parent===item.key&&['field','port'].includes(x.type));for(const f of fields)navButton(f,panel);
 const frow=element('fieldset');frow.append(element('legend','Fields / parameters'));panel.append(frow);const fid=field(frow,'Field ID','field'),fname=field(frow,'Field name','Field'),type=field(frow,'Field datatype','');button('Add field',()=>{M.identifier(fid.value);const group=index().items.find(x=>x.parent===item.key&&x.type==='fields'&&x.group);const code='field '+fid.value+' '+JSON.stringify(fname.value)+(type.value?' {datatype:'+JSON.stringify(type.value)+';}':';');commit(M.append(files(),group||item,group?code:'fields { '+code+' }',A),'Add field');},frow,true);
 const doc=index().items.find(x=>x.parent===item.key&&x.type==='document'&&x.group);button(doc?'Open text document':'Attach / create text document',()=>documentForElement(item),panel,true);
 const comp=index().items.find(x=>x.parent===item.key&&x.type==='composition'&&x.group);compositionEditor(item,comp);
 propertyEditor(item,panel);button('Duplicate definition',()=>{const id=prompt('Identifier for independent copy',item.node.id+'_copy');if(!id)return;M.identifier(id);const text=files()[item.file].slice(item.node.start,item.node.end),tokens=A.lex(text,item.file),token=tokens.find((t,i)=>i>0&&t.value===item.node.id);let copy=M.patches(text,[{start:token.start,end:token.end,text:id}]);if(item.node.props.uid)throw Error('Remove or change the explicit UID in an independent copy using Source');commit(M.append(files(),index().byKey.get(item.parent),copy,A),'Duplicate definition');},panel,true);
 button('Delete definition',()=>{if(confirm('Delete '+item.label+' from the model? References must first be removed.'))commit(M.remove(files(),item,A),'Delete definition');},panel,true);
 }
 function groupProps(next,item,type,values){const idx=M.index(next,A),n=M.find(idx,item),group=idx.items.find(x=>x.parent===n.key&&x.group&&x.type===type);if(group)return M.props(next,group,values,A);const body=type+' { '+Object.entries(values).filter(([,v])=>v!==undefined).map(([k,v])=>k+':'+A.authoring.value(v)+';').join(' ')+' }';return M.append(next,n,body,A);}
 function compositionEditor(item,comp){const box=element('fieldset');box.append(element('legend','Shared element section defaults'));panel.append(box);const p=comp?.node.props||{},parts=p.sections||['name','type','table','notes'],controls={};for(const part of ['name','type','table','notes'])controls[part]=check(box,'Show '+part,parts.includes(part));const order=field(box,'Body order',p.order?.[0]||'table',[{value:'table',label:'Table above notes'},{value:'notes',label:'Notes above table'}]),height=field(box,'Note height',p.note_height?.$quantity||180),wrap=field(box,'Note wrapping',p.note_wrap||'auto',['auto','on','off']);button('Save section defaults',()=>commit(groupProps(upgrade(files(),item.file),item,'composition',{sections:Object.keys(controls).filter(k=>controls[k].checked),order:order.value==='table'?['table','notes']:['notes','table'],note_height:{$quantity:Number(height.value),unit:'px'},note_wrap:wrap.value}),'Set shared sections'),box,true);if(comp)button('Reset to type defaults',()=>commit(M.remove(files(),comp,A),'Reset sections'),box,true);}
 function upgrade(next,file){return {...next,[file]:next[file].replace(/^\s*ddn\s+"[^"]+"\s*;/,'ddn "0.7";')};}
 function addToView(item){const v=viewItem();if(!v)throw Error('Open a view first');let next=files();const blocks=(v.node.props.data||[]).map(r=>M.resolveRef(index(),v,r)).filter(Boolean);let root=item;while(root.parent)root=index().byKey.get(root.parent);if(!blocks.some(b=>b.key===root.key))blocks.push(root);const out=M.ensureRef(next,v,item,A);next=out.files;const ir=state.ws.resolve(v.file,v.view);let selected=v.node.props.select;if(!Array.isArray(selected))selected=ir.view.selected.filter(id=>index().items.some(x=>x.type==='object'&&x.uid===id)).map(id=>({$ref:A.authoring.referenceFor(state.ws,v.file,v.view,id,null)}));next=M.bind(next,v,blocks,undefined,A);next=M.props(next,v,{select:[...selected,out.ref],exclude:(v.node.props.exclude||[]).filter(r=>M.resolveRef(index(),v,r)?.key!==item.key)},A);commit(next,'Add existing definition to view');}
 function openSpecial(type){const labels={models:'Model data',views:'Views',settings:'Shared settings',contents:'View contents',documents:'Text documents',automation:'Automation',publication:'Publication',problems:'Problems',changes:'Workspace changes'};setPanel({key:'section:'+type,type,label:labels[type]||type});
 if(type==='models'){for(const d of index().items.filter(x=>x.type==='data'&&!x.group))navButton(d,panel);createSectionForm('data');}
 if(type==='views'){button('New view',()=>viewForm(),panel,true);for(const v of index().views){const row=element('div',undefined,'ddn-row');navButton(v,row);row.append(element('span',v.file+' · '+v.module,'ddn-dim'));button('Manage',()=>viewForm(v),row,true);panel.append(row);}}
 if(type==='contents')contentsEditor();
 if(type==='settings'){for(const n of index().items.filter(x=>x.type==='format'||x.parent&&index().byKey.get(x.parent)?.type==='format'))navButton(n,panel);createSectionForm('format');profileForm();}
 if(type==='documents'){for(const d of index().documents)button(d.file+' → '+d.id+' ('+M.documentUsers(index(),d.file,d.id,A).length+' references)',()=>openDocument(d.file,d.id),panel);for(const n of index().items.filter(x=>x.group&&x.type==='document'&&!x.node.props.file))button('Inline: '+index().byKey.get(n.parent).label,()=>documentForElement(index().byKey.get(n.parent)),panel);button('New text document',()=>openDocument('',null),panel,true);}
 if(type==='automation')automation();
 if(type==='publication')publication();
 if(type==='problems'){for(const d of ctx.diagnostics()){button((d.code||'')+' '+(d.message||d),()=>ctx.openSource(d.file||d.source?.file||state.entry),panel);}if(!panel.querySelector('button:not(.ddn-workspace-heading button)'))panel.append(element('p','No reported problems.'));}
 if(type==='changes'){const now=files(),paths=new Set([...Object.keys(now),...Object.keys(state.saved)]);let count=0;for(const f of [...paths].sort())if(now[f]!==state.saved[f]){count++;const d=element('details');d.append(element('summary',(now[f]===undefined?'Deleted: ':state.saved[f]===undefined?'Added: ':'Modified: ')+f));d.append(element('h3','Saved'),element('pre',state.saved[f]||''),element('h3','Current'),element('pre',now[f]||''));panel.append(d);}panel.append(element('p',count+' file(s) changed since save'));}
 }
 function createSectionForm(type){const box=element('fieldset');box.append(element('legend','New '+type+' section'));panel.append(box);const file=field(box,'Section file',state.entry),module=field(box,'Section module',index().docs.get(state.entry)?.module||'model'),id=field(box,'Section ID',type==='data'?'model':'formats');button('Create '+type,()=>{M.identifier(id.value);A.pathChecked(file.value);let next=files();if(!next[file.value])next={...next,[file.value]:'ddn "0.7";\nmodule '+JSON.stringify(module.value)+';\n'};const idx=M.index(next,A),doc=idx.docs.get(file.value),sec=doc?.sections?.find(s=>s.module===module.value);if(!sec)throw Error('Module not found');if(sec.declarations.some(n=>n.id===id.value))throw Error('Section ID already exists');const at=sec.declarations.at(-1)?.end??next[file.value].length;next={...next,[file.value]:M.patches(next[file.value],[{start:at,end:at,text:'\n'+type+' '+id.value+' {}\n'}])};commit(next,'Create '+type+' section');},box,true);}
 function profileForm(){const formats=index().items.filter(x=>x.type==='format');if(!formats.length)return;const box=element('fieldset');box.append(element('legend','New reusable profile'));panel.append(box);const owner=field(box,'Format section',formats[0].key,formats.map(x=>({value:x.key,label:x.file+' / '+x.path}))),type=field(box,'Profile concern','layout',['projection','notation','layout','style','display','publication','legend','chrome','validation','export','bundle']),id=field(box,'Profile ID','shared');button('Create profile',()=>{M.identifier(id.value);commit(M.append(files(),owner.value,type.value+' '+id.value+' {}',A),'Create reusable profile');},box,true);}
 function viewForm(v=null){setPanel({key:'view-form:'+(v?.key||'new'),type:'view-form',managed:v?.key,label:v?'Manage '+v.label:'New view'});const file=field(panel,'View file',v?.file||state.entry),module=field(panel,'View module',v?.module||index().docs.get(state.entry)?.module||'views'),id=field(panel,'View identifier',v?.node.id||'new_view'),caption=field(panel,'View name',v?.label||'New view'),kind=field(panel,'View kind',v?.node.props.kind||'', [{value:'',label:'Unspecified'},...Object.keys(A.viewProfiles.VIEW_KINDS)]);
 const blocks=index().items.filter(x=>x.type==='data'&&!x.group&&!/\.ddna(?:\.ddn)?$/.test(x.file)),checks=blocks.map(b=>[b,check(panel,'Use '+b.file+' / '+b.module+'::'+b.path,!!v&&(v.node.props.data||[]).some(r=>M.resolveRef(index(),v,r)?.key===b.key))]);
 if(v){button('Save view name / identifier',()=>{let next=M.label(files(),v,caption.value,A);next=M.props(next,v,{kind:kind.value||undefined},A);next=M.rename(next,v,id.value,A);commit(next,'Rename view',{file:v.file,view:v.module+'::'+id.value});},panel,true);button('Duplicate view over shared data',()=>{const next=M.createView(files(),{file:file.value,module:module.value,id:id.value,label:caption.value,copy:v},A);commit(next.files,'Duplicate view',{file:file.value,view:module.value+'::'+id.value});},panel,true);button('Delete view',()=>{if(confirm('Delete view '+v.label+'? Model definitions and text documents are retained.'))commit(M.remove(files(),v,A),'Delete view');},panel,true);button('Edit contents',()=>{openView(v);openSpecial('contents');},panel);}
 else button('Create view',()=>{const out=M.createView(files(),{file:file.value,module:module.value,id:id.value,label:caption.value,kind:kind.value,blocks:checks.filter(([,c])=>c.checked).map(([b])=>b)},A);commit(out.files,'Create view',{file:file.value,view:module.value+'::'+id.value});},panel,true);
 }
 function contentsEditor(){const v=viewItem();if(!v){panel.append(element('p','Create or open a view first.'));return;}panel.append(element('p','Editing '+v.label+' in '+v.file));const idx=index(),ir=state.ws.resolve(v.file,v.view),blocks=idx.items.filter(x=>x.type==='data'&&!x.group&&!/\.ddna(?:\.ddn)?$/.test(x.file));const checks=blocks.map(b=>[b,check(panel,'Bind '+b.file+' / '+b.module+'::'+b.path,(v.node.props.data||[]).some(r=>M.resolveRef(idx,v,r)?.key===b.key))]);
 button('Apply data bindings',()=>{const chosen=checks.filter(([,c])=>c.checked).map(([b])=>b);let next=M.bind(files(),v,chosen,undefined,A);if(!Array.isArray(v.node.props.select)){const refs=ir.view.selected.filter(id=>index().items.some(x=>x.type==='object'&&x.uid===id)).map(id=>({$ref:A.authoring.referenceFor(state.ws,v.file,v.view,id,null)}));next=M.props(next,v,{select:refs},A);}commit(next,'Change view data bindings');},panel,true);
 panel.append(element('h3','Visible definitions'));const selected=ir.elements.filter(n=>idx.items.some(x=>x.type==='object'&&x.uid===n.id)).map(n=>[n,check(panel,'Include '+n.id,ir.view.selected.includes(n.id))]);button('Apply visible definitions',()=>{const selectedIds=new Set(selected.filter(([,c])=>c.checked).map(([n])=>n.id));ctx.visibility(selectedIds);drafts.delete(active.key);openSpecial('contents');},panel,true);
 panel.append(element('h3','Appearances'));for(const occurrence of A.authoring.occurrences(state.ws,v.file,v.view).elements||[]){const row=element('div',undefined,'ddn-row');row.append(element('span',occurrence.source+' #'+occurrence.number));button('Properties',()=>{openView(v);ctx.select(occurrence.id);ctx.drawer('inspector');},row);button('Another appearance',()=>ctx.author('addOccurrence',[occurrence.id]),row,true);button('Remove from this view',()=>ctx.author('hide',[occurrence.id]),row,true);panel.append(row);}
 profileBindings(v,ir);
 }
 function profileBindings(v,ir){panel.append(element('h3','Reusable settings and effective values'));for(const concern of ['bundle','projection','notation','style','layout','display','publication','legend','chrome','validation','export']){const key=concern==='bundle'?'format':concern,profiles=index().items.filter(x=>x.type===concern&&!x.group&&index().byKey.get(x.parent)?.type==='format'),current=M.resolveRef(index(),v,v.node.props[key]);const select=field(panel,concern+' profile',current?.key||'',[{value:'',label:'Default / no shared reference'},...profiles.map(p=>({value:p.key,label:p.file+' / '+p.path}))]);button('Apply '+concern+' reference',()=>{let next=files(),ref;if(select.value){const out=M.ensureRef(next,v,select.value,A);next=out.files;ref=out.ref;}commit(M.props(next,v,{[key]:ref},A),'Bind '+concern+' profile');},panel,true);if(current)button('Edit shared '+concern,()=>openItem(current),panel);
 if(concern!=='bundle'){const local=v.node.children.find(c=>c.group&&c.type===concern);const values=ir.view.profiles[concern]||{},bundle=M.resolveRef(index(),v,v.node.props.format),inherited=current||(bundle&&M.resolveRef(index(),bundle,bundle.node.props[concern]));const table=element('table',undefined,'ddn-data-table');for(const [name,value]of Object.entries(values)){const tr=element('tr');tr.append(element('td',name),element('td',jsonValue(value)),element('td',Object.hasOwn(local?.props||{},name)?'This view':inherited&&Object.hasOwn(inherited.node.props,name)?'Inherited from '+inherited.file+' / '+inherited.path:'Inherited default / derived'));const td=element('td');if(Object.hasOwn(local?.props||{},name))button('Reset',()=>{const group=index().items.find(x=>x.file===v.file&&x.node.start===local.start);commit(M.props(files(),group,{[name]:undefined},A),'Reset inherited value');},td,true);tr.append(td);table.append(tr);}const name=field(panel,concern+' override property',''),value=field(panel,concern+' override value','');button('Set '+concern+' override',()=>{if(!name.value)throw Error('Choose a property');commit(groupProps(files(),v,concern,{[name.value]:JSON.parse(value.value)}),'Override '+concern);},panel,true);panel.append(table);}}
 }
 function openDocument(file,id){setPanel({key:'document:'+M.key(file,'',id||''),type:'text-document',file,id,label:id||'New text document'});const existing=id?index().docs.get(file)?.documents?.[id]:null;if(id&&!existing)throw Error('Document is missing');documentEditor(existing||{format:'plain',role:'note',text:''},file,id,null);}
 function documentForElement(item){setPanel({key:'text:'+item.key,type:'item',item:item.key,file:item.file,label:'Text — '+item.label});const doc=index().items.find(x=>x.parent===item.key&&x.group&&x.type==='document'),p=doc?.node.props||{};let record=p,file='',id='';if(p.file){file=A.resolvePath(item.file,p.file);id=p.id;record=index().docs.get(file)?.documents?.[id];if(!record)throw Error('Referenced document is missing');}documentEditor(record.text===undefined?{format:'plain',role:'note',text:item.node.props.description||''}:record,file,id,item);}
 function documentEditor(record,file,id,owner){const format=field(panel,'Text format',record.format||'plain',['plain','markdown_text','code']),role=field(panel,'Text role',record.role||'note',['note','procedure_source','function_source','source']),lang=field(panel,'Code language',record.language||''),text=field(panel,'Document text',record.text||'','text');text.classList.add('ddn-document-text');text.wrap='off';const path=field(panel,'Storage file',file||''),key=field(panel,'Document ID',id||'body');panel.append(element('p',owner?'Blank storage file keeps text inline. Paths here are workspace-relative. Saving to an existing record edits every reference to that record.':'Choose a .ddnn workspace file and stable record ID.','ddn-dim'));
 const uses=file?M.documentUsers(index(),file,id,A):owner?[owner]:[];panel.append(element('p','Referenced by '+uses.length+' definition(s)'));for(const u of uses)navButton(u,panel);
 const attach=field(panel,'Attach existing document','',[{value:'',label:'Choose a document'},...index().documents.map(d=>({value:d.key,label:d.file+' / '+d.id}))]);if(owner)button('Attach selected document',()=>{const d=index().documents.find(d=>d.key===attach.value);if(!d)throw Error('Choose a document');setDocumentReference(owner,d.file,d.id);},panel,true);
 button('Save text document',()=>{const rec={format:format.value,role:role.value,text:text.value,...(lang.value?{language:lang.value}:{})};let next=files();const dest=path.value.trim(),docId=key.value.trim();if(dest){A.pathChecked(dest);if(!dest.endsWith('.ddnn')||!docId||['__proto__','constructor','prototype'].includes(docId))throw Error('Choose a .ddnn path and nonreserved document ID');const content=next[dest]?A.documentFormats.read(next[dest]):{format:'ddnn@1',documents:{}};const replacing=content.documents[docId]&&!(dest===file&&docId===id);if(replacing&&!confirm('Replace existing shared document '+docId+' in '+dest+'?'))return;content.documents[docId]=rec;next={...next,[dest]:JSON.stringify(content,null,2)+'\n'};
 // Expected digests on all references must follow an intentional shared edit.
 for(const u of M.documentUsers(index(),dest,docId,A)){const g=index().items.find(x=>x.parent===u.key&&x.group&&x.type==='document');if(g.node.props.digest)next=M.props(next,g,{digest:A.documentFormats.digest(rec.text)},A);}
 }
 if(owner){next=upgrade(next,owner.file);const idx=M.index(next,A),g=idx.items.find(x=>x.parent===owner.key&&x.type==='document'&&x.group);const code='document { '+Object.entries(dest?{file:A.relative(owner.file,dest),id:docId}:rec).map(([k,v])=>k+':'+A.authoring.value(v)+';').join(' ')+' }';next=g?{...next,[owner.file]:M.patches(next[owner.file],[{start:g.node.start,end:g.node.end,text:code}])}:M.append(next,owner,code,A);}else if(!dest)throw Error('A library document needs a .ddnn file');commit(next,'Edit text document');},panel,true);
 if(owner)button('Detach text',()=>{const g=index().items.find(x=>x.parent===owner.key&&x.type==='document'&&x.group);if(g)commit(M.remove(files(),g,A),'Detach text document');},panel,true);
 if(file)button('Delete unreferenced document',()=>{if(uses.length)throw Error('Detach all references first');const content=A.documentFormats.read(files()[file]);delete content.documents[id];commit({...files(),[file]:JSON.stringify(content,null,2)+'\n'},'Delete text document');},panel,true);
 }
 function setDocumentReference(owner,file,id){let next=upgrade(files(),owner.file);const idx=M.index(next,A),g=idx.items.find(x=>x.parent===owner.key&&x.type==='document'&&x.group);const code='document {file:'+JSON.stringify(A.relative(owner.file,file))+';id:'+JSON.stringify(id)+';}';next=g?{...next,[owner.file]:M.patches(next[owner.file],[{start:g.node.start,end:g.node.end,text:code}])}:M.append(next,owner,code,A);commit(next,'Attach document');}
 function openRules(file){setPanel({key:'rules:'+file,type:'rules',file,label:'Rules — '+file});const box=element('div');panel.append(box);ctx.editRules(file,box,drafts.get(active.key)?.features,features=>{drafts.set(active.key,{revision:panelRevision,features,values:{}});renderTabs();},next=>commit(next,'Edit automation rules'));}
 function automation(){panel.append(element('p','Automation definitions and replay are local to this workspace. Stored source-code text is inert.'));button('Open evaluation and replay',()=>ctx.drawer('animation'),panel);button('Create rules for selected element',()=>ctx.createRules(),panel,true);
 for(const [file,text]of Object.entries(files()))if(ctx.isCompanion(file,text)){const box=element('fieldset');box.append(element('legend',file));for(const base of ctx.served(file))box.append(element('p','Identity base: '+base));button('Open definitions',()=>ctx.openSource(file),box);button('Edit supported rules',()=>openRules(file),box,true);panel.append(box);}
 for(const item of index().items.filter(x=>x.type==='architecture'||x.node.props.x_profile||x.node.props.x_keel||x.node.props.x_trace))navButton(item,panel);
 for(const [file,text]of Object.entries(state.traceFiles||{})){const d=element('details');d.append(element('summary','Trace: '+file),element('pre',text));panel.append(d);}}
 function publication(){panel.append(element('p','Save preserves source, companions and full text. Export produces the selected presentation.'));button('View page / header / footer settings',()=>ctx.drawer('document'),panel);button('Export current view',()=>ctx.drawer('export'),panel);button('Save complete workspace',()=>ctx.save(false),panel,true);const v=viewItem();if(v){const mode=field(panel,'Published notes',state.ws.resolve(v.file,v.view).view.profiles.publication.note_mode||'viewport',[{value:'viewport',label:'Viewport excerpt'},{value:'full',label:'Complete text'}]);button('Save note publication mode',()=>commit(groupProps(upgrade(files(),v.file),v,'publication',{note_mode:mode.value}),'Change note publication'),panel,true);}for(const n of index().items.filter(x=>x.type==='publication'&&!x.group))navButton(n,panel);}
 function commit(next,label,target){if(!state.config.design)throw Error('Editing requires design mode');if(panelRevision!==state.ws.revision)throw Error('The workspace changed while this editor was open. Your draft is retained. Reopen or discard it before applying.');const idx=M.index(next,A);if(idx.errors.length)throw idx.errors[0].error;const chosen=target?idx.views.find(v=>v.file===target.file&&(v.view===target.view||v.uid===target.view)):idx.views.find(v=>v.file===state.entry&&(v.view===state.view||v.uid===state.view))||idx.views[0];if(!chosen)throw Error('Keep at least one view in the workspace');const previous=active?.managed;ctx.commit(next,label,chosen);const remembered=previous&&sessions.get(previous);if(target&&previous&&!idx.byKey.has(previous)&&remembered){sessions.set(chosen.key,remembered);sessions.delete(previous);}drafts.delete(active?.key);panelRevision=state.ws.revision;cached=null;refresh();if(target)openView(M.find(index(),chosen));else if(active?.type==='item'&&!index().byKey.has(active.item))openSpecial('models');else if(active?.type==='text-document'&&!index().docs.get(active.file)?.documents?.[active.id])openSpecial('documents');else if(active)activate(active);}
 function beforeMount(){const v=viewItem();if(!v)return null;const key=v.key;if(lastView&&lastView!==key){const stage=ctx.stage();sessions.set(lastView,{fit:state.fit,zoom:state.zoom,selected:state.selected,selectedRelation:state.selectedRelation,selectedIds:[...state.selectedIds],presentation:structuredClone(state.presentation),scroll:[stage?.scrollLeft||0,stage?.scrollTop||0],layout:state.diagram?._layoutState});const remembered=sessions.get(key);state.fit=remembered?.fit||'page';state.zoom=remembered?.zoom??null;state.selected=remembered?.selected||null;state.selectedRelation=remembered?.selectedRelation||null;state.selectedIds=remembered?.selectedIds||[];state.presentation=remembered?.presentation||ctx.emptyPresentation();pendingScroll=remembered?.scroll||[0,0];}
 lastView=key;if(!active||active.type==='view'){active={key:'view:'+key,type:'view',item:key,label:v.label,file:v.file};rememberTab(active);}return sessions.get(key)?.layout||null;}
 function rendered(){if(pendingScroll){const st=ctx.stage();if(st){[st.scrollLeft,st.scrollTop]=pendingScroll;}pendingScroll=null;}selection();}
 function appearanceSignature(){const values=new Map([...sessions].map(([k,v])=>[k,v.presentation]));const v=viewItem();if(v)values.set(v.key,state.presentation);const empty=JSON.stringify(ctx.emptyPresentation());return JSON.stringify([...values].filter(([k,p])=>index().byKey.has(k)&&JSON.stringify(p)!==empty).sort((a,b)=>a[0].localeCompare(b[0])));}
 function snapshot(){
 const v=viewItem(),stage=ctx.stage();if(v)sessions.set(v.key,{fit:state.fit,zoom:state.zoom,selected:state.selected,selectedRelation:state.selectedRelation,selectedIds:[...state.selectedIds],presentation:structuredClone(state.presentation),scroll:[stage?.scrollLeft||0,stage?.scrollTop||0],layout:state.diagram?._layoutState});
 return {version:1,tabs:tabs.filter(t=>t.type==='view').map(t=>t.item),sessions:[...sessions]};
 }
 function restore(saved){
 if(saved?.version!==1)return;const idx=index();
 for(const pair of (Array.isArray(saved.sessions)?saved.sessions:[]).slice(0,200)){if(!Array.isArray(pair)||!idx.byKey.has(pair[0])||!pair[1]||typeof pair[1]!=='object')continue;const p=pair[1];sessions.set(pair[0],{fit:['page','width','height','100'].includes(p.fit)?p.fit:'page',zoom:Number.isFinite(p.zoom)?Math.min(8,Math.max(.05,p.zoom)):null,selected:typeof p.selected==='string'?p.selected:null,selectedRelation:typeof p.selectedRelation==='string'?p.selectedRelation:null,selectedIds:Array.isArray(p.selectedIds)?p.selectedIds.filter(x=>typeof x==='string'):[],presentation:ctx.checkPresentation(p.presentation),scroll:Array.isArray(p.scroll)?p.scroll.map(x=>Number.isFinite(x)?Math.max(0,x):0).slice(0,2):[0,0],layout:p.layout||null});}
 tabs=(Array.isArray(saved.tabs)?saved.tabs:[]).slice(0,200).filter(k=>idx.byKey.get(k)?.type==='view').map(k=>{const v=idx.byKey.get(k);return {key:'view:'+k,type:'view',item:k,label:v.label,file:v.file};});
 const v=viewItem(),p=v&&sessions.get(v.key);if(p){state.fit=p.fit;state.zoom=p.zoom;state.presentation=p.presentation;state.selected=p.selected;state.selectedRelation=p.selectedRelation;state.selectedIds=p.selectedIds;pendingScroll=p.scroll;}
 }
 function reset(){cached=null;revision=-1;workspace=null;active=null;tabs=[];lastView=null;sessions.clear();drafts.clear();panel.hidden=true;$('ddn-stage').hidden=false;}
 // Leaving an editor retains its draft, while explicitly discarding reloads it.
 button('Discard editor draft',()=>{if(active){drafts.delete(active.key);activate(active);}},footer,true);
 return {appearanceSignature,hasDrafts:()=>drafts.size>0,refresh,index,reset,snapshot,restore,beforeMount,rendered,selection,openView,openSpecial,openItem,viewForm,commit,documentForElement};
}
host.DDNWorkspaceUI={create};
})(typeof globalThis!=='undefined'?globalThis:this);
