/* SPDX-License-Identifier: GPL-2.0-or-later. Matrix pack: matrix.bcg@1 / matrix.ansoff@1 / matrix.tows@1 quadrant profiles. */
'use strict';
const A=require('../dist/ddn.global.js'), assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const dir=path.resolve(__dirname,'../../examples/basics'),base={'33-matrix-pack.ddn':fs.readFileSync(dir+'/33-matrix-pack.ddn','utf8'),'shared.ddn':fs.readFileSync(dir+'/shared.ddn','utf8')};
const results=[];function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,code:e.code,message:e.message});console.error('FAIL',name,e.stack);}}
function workspace(changes={}){return A.createWorkspace({...base,...changes});}
function run(view,changes={}){return workspace(changes).renderSync({entry:'33-matrix-pack.ddn',view});}
const throws=(fn,code)=>assert.throws(fn,e=>{if(code&&e.code!==code)console.error('Expected',code,'got',e.code,e.message);return code?e.code===code:typeof e.code==='string';});
const editFile=(before,after)=>{assert.ok(base['33-matrix-pack.ddn'].includes(before),'Mutation target missing');return{'33-matrix-pack.ddn':base['33-matrix-pack.ddn'].replace(before,after)};};
test('BCG renders a 2x2 plan with declared products in the star quadrant and the caption',()=>{const r=run('bcg');assert.match(r.svg,/<svg/);assert.ok(r.svg.includes('GROWTH / SHARE MATRIX'));assert.ok(r.svg.includes('Sparkling tea'));assert.ok(r.svg.includes('Classic cola'));const plan=workspace().projectionPlan('33-matrix-pack.ddn','bcg');assert.equal(plan.rows.length,2);assert.equal(plan.columns.length,2);assert.equal(plan.cells.length,2);assert.equal(plan.cells[0].length,2);const star=plan.cells[0][0];assert.ok(star.length>=1);assert.ok(star.some(c=>c.value==='Sparkling tea'));});
test('Ansoff renders with its caption and expected cell placements',()=>{const r=run('ansoff');assert.ok(r.svg.includes('PRODUCT / MARKET MATRIX'));assert.ok(r.svg.includes('Botanical tonic line'));const plan=workspace().projectionPlan('33-matrix-pack.ddn','ansoff');assert.equal(plan.rows.length,2);assert.equal(plan.columns.length,2);assert.equal(plan.cells[0][1][0].value,'Botanical tonic line');assert.equal(plan.cells[1][0][0].value,'Coastal export launch');});
test('TOWS renders with its caption and expected cell placements',()=>{const r=run('tows');assert.ok(r.svg.includes('TOWS STRATEGY MATRIX'));const plan=workspace().projectionPlan('33-matrix-pack.ddn','tows');assert.equal(plan.rows.length,2);assert.equal(plan.columns.length,2);assert.equal(plan.cells[0][0][0].value,'Use brand strength in subscription channel');assert.equal(plan.cells[1][1][0].value,'Hedge sweetener sourcing before levy passes');});
test('Two products in one BCG quadrant render joined with both IDs kept',()=>{const plan=workspace().projectionPlan('33-matrix-pack.ddn','bcg'),star=plan.cells[0][0];assert.equal(star.length,2);assert.deepEqual(star.map(c=>c.value),['Sparkling tea','Ginger sparkler']);assert.equal(new Set(star.map(c=>c.id)).size,2);const r=run('bcg');assert.ok(r.svg.includes('Sparkling tea / Ginger sparkler'));});
test('Unknown quadrant level rejected as DDN-PJ082',()=>throws(()=>run('bcg',editFile('x_category: {axis:"growth", level:"high"}','x_category: {axis:"growth", level:"medium"}')),'DDN-PJ082'));
test('Missing x_category on a column rejected as DDN-PJ082 naming the element',()=>{const e=editFile('object s_high "Relative share: high" { kind: record; x_category: {axis:"share", level:"high"};','object s_high "Relative share: high" { kind: record;');throws(()=>run('bcg',e),'DDN-PJ082');assert.throws(()=>run('bcg',e),e=>e.message.includes('Relative share: high'));});
test('A third row category rejected as DDN-PJ082 by the count check',()=>throws(()=>run('bcg',editFile('rows:[@axes.g_high, @axes.g_low];','rows:[@axes.g_high, @axes.g_low, @axes.m_existing];')),'DDN-PJ082'));
test('Duplicate level on two rows rejected as DDN-PJ082',()=>throws(()=>run('bcg',editFile('x_category: {axis:"growth", level:"low"}','x_category: {axis:"growth", level:"high"}')),'DDN-PJ082'));
test('Two relations into one cell without duplicates:join stay DDN-PJ015',()=>throws(()=>run('bcg',editFile('relation:"assoc"; value:"name"; duplicates:join; }','relation:"assoc"; value:"name"; }')),'DDN-PJ015'));
test('Quadrant profile on the wrong projection kind rejected',()=>throws(()=>run('bcg',editFile('projection { kind:matrix; profile:"matrix.bcg@1"','projection { kind:panels; profile:"matrix.bcg@1"')),'DDN-PF002'));
test('RACI still rejects duplicates:join as DDN-PJ014',()=>{const source='ddn "0.4";module "mini.raci";data m { object task "Approve order" { kind: "flow.process"; } object buyer "Buyer" { kind: "analysis.role"; } relation r1 @task -> @buyer { kind:"analysis.assignment"; x_assignment:{code:"A"}; } relation r2 @task -> @buyer { kind:"analysis.assignment"; x_assignment:{code:"R"}; } }view v { data:[@m]; projection { kind:matrix; profile:"matrix.raci@1"; rows:[@m.task]; columns:[@m.buyer]; relation:"analysis.assignment"; value:"x_assignment.code"; duplicates:join; } }';throws(()=>A.createWorkspace({'main.ddn':source}).renderSync({entry:'main.ddn',view:'v'}),'DDN-PJ014');});
test('Deterministic rerender of the bcg view',()=>assert.equal(run('bcg').svg,run('bcg').svg));
const passed=results.filter(r=>r.pass).length;console.log(`Matrix pack ${passed}/${results.length}`);if(passed!==results.length)process.exitCode=1;
