/* SPDX-License-Identifier: GPL-2.0-or-later. Public-path fixtures for the 0.4 expansion. */
'use strict';
const A=require('../dist/ddn.global.js'), assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=path.resolve(__dirname,'../../website/examples/projections'),base=Object.fromEntries(['model.ddn','views.ddn','formats.ddn'].map(f=>[f,fs.readFileSync(path.join(dir,f),'utf8')])),catalogue=JSON.parse(fs.readFileSync(dir+'/catalogue.json','utf8'));
const results=[],renders=[];function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,code:e.code,message:e.message});console.error('FAIL',name,e.stack);}}
function workspace(changes={}){return A.createWorkspace({...base,...changes});}
function run(view='chart_bar',changes={},overrides={}){return workspace(changes).renderSync({entry:'views.ddn',view,overrides});}
const editModel=(before,after)=>{assert.ok(base['model.ddn'].includes(before),'Mutation target missing');return{'model.ddn':base['model.ddn'].replace(before,after)};};
const editView=(view,oldValue,newValue)=>{const text=base['views.ddn'],start=text.indexOf('view '+view+' '),end=text.indexOf('\nview ',start+1),block=text.slice(start,end<0?undefined:end);assert.ok(block.includes(oldValue),'View mutation target missing');return{'views.ddn':text.slice(0,start)+block.replace(oldValue,newValue)+(end<0?'':text.slice(end))};};
const throws=(fn,code)=>assert.throws(fn,e=>{if(code&&e.code!==code)console.error('Expected',code,'got',e.code,e.message);return code?e.code===code:typeof e.code==='string';});
const getPlan=(view,changes={})=>workspace(changes).projectionPlan('views.ddn',view);
const recordId=short=>'meridian.procurement.review::'+short;
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
for(const item of catalogue){const view=item.id||item.view;test('Compiles '+view,()=>{const r=run(view);assert.match(r.svg,/<svg/);assert.ok(r.svg.includes('</svg>'));assert.ok(r.scene.width>0&&r.scene.height>0);assert.equal(r.profiles.projection.profile,item.profile||r.profiles.projection.profile);renders.push({view,svgSHA256:sha(r.svg),modelFingerprint:r.modelFingerprint,marks:r.scene.marks?.length||0,nodes:r.scene.nodes.length,diagnostics:r.diagnostics});});}
for(const v of ['flowchart','raci','chart_bar','gantt','swot'])for(const look of ['handDrawn','neo'])test('Look preserves model: '+v+'/'+look,()=>{const a=run(v),b=run(v,{}, {look,theme:'night'});assert.equal(a.modelFingerprint,b.modelFingerprint);assert.notEqual(a.svg,b.svg);if(a.scene.marks)assert.deepEqual(a.scene.marks,b.scene.marks);});
test('All profiles identified; versions and projection list exposed',()=>{assert.equal(A.VERSION,require('../package.json').version);assert.deepEqual(A.profileCatalogue,JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../standard/registry/profiles/catalogue.json'),'utf8')));assert.ok(A.profileCatalogue.profiles.length>=15);assert.ok(A.profileCatalogue.kinds.length>=24);});
test('Deterministic rerender',()=>assert.equal(run('raci').svg,run('raci').svg));
test('Source files are never rewritten by rendering',()=>{const w=workspace(),before=w.getFiles();for(const v of ['flowchart','raci','chen','gantt'])w.renderSync({entry:'views.ddn',view:v});assert.deepEqual(before,w.getFiles());});
test('0.5 resolved identity, legacy core registry separate',()=>{const ir=workspace().resolve('views.ddn','raci');assert.equal(ir.language,'0.5');assert.equal(ir.registry,'ddn-core@0.3');assert.equal(ir.format,'ddn-resolved@0.5');});
test('ER and Chen reuse one semantic fingerprint',()=>assert.equal(run('erd').modelFingerprint,run('chen').modelFingerprint));
test('Chen appearances identify existing fields and relationships',()=>{const r=run('chen'),ir=workspace().resolve('views.ddn','chen'),known=new Set([...ir.elements.map(x=>x.id),...ir.elements.flatMap(n=>n.fields.map(f=>f.id)),...ir.relations.map(x=>x.id)]);for(const m of r.scene.projection.mapping)assert.ok(known.has(m.source));assert.ok(r.scene.nodes.some(n=>n.id===recordId('schema.po.order_id')));});
test('RACI and graph use same relationship identities',()=>{const r=run('raci'),ir=workspace().resolve('views.ddn','responsibility_graph');for(const m of r.scene.marks.filter(m=>m.property==='x_assignment.code'))for(const id of m.sourceIds)assert.ok(ir.relations.some(r=>r.id===id));});
test('RACI values and accountability',()=>{const p=getPlan('raci');assert.equal(p.cells[0][0][0].value,'R');for(const row of p.cells){assert.equal(row.flat().filter(c=>c.value==='A').length,1);assert.ok(row.flat().some(c=>c.value==='R'));}});
test('RACI missing A rejected',()=>throws(()=>run('raci',editModel('code:"A"','code:"I"')),'DDN-PJ016'));
test('RACI two As rejected',()=>throws(()=>run('raci',editModel('code:"R"','code:"A"')),'DDN-PJ016'));
test('RACI unknown code rejected',()=>throws(()=>run('raci',editModel('code:"R"','code:"Z"')),'DDN-PJ016'));
test('CRUD repeated operation rejected',()=>throws(()=>run('crud',editModel('code:"CR"','code:"RR"')),'DDN-PJ017'));
test('Duplicate assignment cell rejected',()=>{const m=base['model.ddn'].replace('data responsibilities {','data responsibilities { relation dupe @process.order -> @roles.buyer {kind:"analysis.assignment";x_assignment:{code:"C"};}');throws(()=>run('raci',{'model.ddn':m}),'DDN-PJ015');});
test('Explicit relation-cell join retains all IDs',()=>{const m=base['model.ddn'].replace('data responsibilities {','data responsibilities { relation dupe "Second opinion" @process.order -> @roles.buyer {kind:"analysis.assignment";x_assignment:{code:"C"};}'),v=editView('matrix_general','value:"name";','value:"name";duplicates:join;');const p=getPlan('matrix_general',{...v,'model.ddn':m});assert.equal(p.cells[0][0].length,2);});
test('Excluded row reference rejected',()=>throws(()=>run('raci',editView('raci','format: @f.shared.common;','format: @f.shared.common;exclude:[@m.process.order];')),'DDN-PJ008'));
test('No invented records when chart bindings duplicated',()=>throws(()=>run('chart_bar',editView('chart_bar','@m.facts.m2','@m.facts.m1')),'DDN-PJ009'));
test('Unknown profile rejected',()=>throws(()=>run('raci',editView('raci','matrix.raci@1','matrix.racy@1')),'DDN-PF001'));
test('Projection/profile mismatch rejected',()=>throws(()=>run('raci',editView('raci','kind:matrix','kind:chart')),'DDN-PF002'));
test('Unused property is not silently accepted',()=>throws(()=>run('raci',editView('raci','kind:matrix;','kind:matrix;mark:pie;')),'DDN-PJ005'));
test('Graph pins prohibited for chart coordinates',()=>throws(()=>run('chart_bar',editView('chart_bar','format: @f.shared.common;','format: @f.shared.common;place @m.facts.m1 {at:[0px,0px];}')),'DDN-PJ002'));
test('Chart pin inspector refused',()=>throws(()=>A.authoring.pin(workspace(),'views.ddn','chart_bar',recordId('facts.m1'),0,0),'DDN-E006'));
test('Graph controls not advertised for matrices/charts/timelines',()=>{for(const v of ['raci','chart_bar','gantt','chen']){const cap=workspace().inspect('views.ddn',v).capabilities;assert.equal(cap.autoPlacement,false);assert.deepEqual(cap.placement,['source']);}});
test('Source graph remains dynamically routable',()=>assert.equal(workspace().inspect('views.ddn','flowchart').capabilities.autoPlacement,true));
test('Chart appearance override does not become value edit',()=>{const a=run('chart_bar'),b=run('chart_bar',{}, {mark:'pie'});assert.equal(a.modelFingerprint,b.modelFingerprint);assert.equal(b.scene.projection.kind,'chart');assert.ok(b.scene.marks[0].endAngle);});
test('Non-chart mark override rejected',()=>throws(()=>run('raci',{}, {mark:'pie'})));
test('Numeric line cannot silently become categorical bar',()=>throws(()=>run('scatter',{}, {mark:'bar'})));
test('Unsafe property selector rejected',()=>throws(()=>run('chart_bar',editView('chart_bar','x_record.value','constructor.name')),'DDN-PJ004'));
test('Numeric strings rejected',()=>throws(()=>run('chart_bar',editModel('"value": 420','"value": "420"')),'DDN-PJ032'));
test('Mixed declared units rejected',()=>throws(()=>run('chart_bar',editModel('"unit": "CAD"','"unit": "USD"')),'DDN-PJ034'));
test('Duplicate categories require aggregate',()=>throws(()=>run('chart_bar',editModel('"month": "Feb"','"month": "Jan"')),'DDN-PJ036'));
test('Explicit sum groups retain source IDs',()=>{const c={...editModel('"month": "Feb"','"month": "Jan"'),...editView('chart_bar','mark:bar;','mark:bar;aggregate:sum;')},p=getPlan('chart_bar',c);assert.equal(p.points[0].y,990);assert.equal(p.points[0].sourceIds.length,2);});
test('Count cannot wear input currency unit',()=>throws(()=>run('chart_bar',editView('chart_bar','mark:bar;','mark:bar;aggregate:count;')),'DDN-PJ034'));
test('Nonnegative arc constraint',()=>throws(()=>run('chart_pie',editModel('"value": 420','"value": -420')),'DDN-PJ037'));
test('Pie zero total rejected',()=>throws(()=>run('chart_pie',{'model.ddn':base['model.ddn'].replace(/"value": \d+/g,'"value": 0')}),'DDN-PJ037'));
test('Single-category pie emits complete circle geometry',()=>{const v=editView('chart_pie','@m.facts.m1, @m.facts.m2, @m.facts.m3, @m.facts.m4, @m.facts.m5, @m.facts.m6','@m.facts.m1'),r=run('chart_pie',v),m=r.scene.marks[0];assert.ok(Math.abs(m.endAngle-m.startAngle-Math.PI*2)<1e-12);assert.match(r.svg,/A[\d.]+ [\d.]+ 0 0 1/);});
test('Pie angular span proportional to values',()=>{const r=run('chart_pie');for(const m of r.scene.marks){assert.ok(Math.abs((m.endAngle-m.startAngle)/(Math.PI*2)-m.value/3750)<1e-10);}});
test('Bubble area proportional to size',()=>{const r=run('scatter'),m=r.scene.marks;assert.ok(Math.abs((m[0].w*m[0].w)/(m[1].w*m[1].w)-8/10)<1e-10);});
test('Negative bar extends below baseline without losing value',()=>{const r=run('chart_bar',editModel('"value": 420','"value": -420')),a=r.scene.marks[0];assert.equal(a.value,-420);assert.ok(a.h>0);});
test('Missing numeric values error by default',()=>throws(()=>run('chart_bar',editModel('"value": 420','"other": 420')),'DDN-PJ032'));
test('Explicit skip records provenance of missing rows',()=>{const c={...editModel('"value": 420','"other": 420'),...editView('chart_bar','mark:bar;','mark:bar;missing:skip;')},p=getPlan('chart_bar',c);assert.deepEqual(p.skipped,[recordId('facts.m1')]);assert.equal(p.points.length,5);});
test('Date validates calendar rather than parser rollover',()=>throws(()=>run('time_series',editModel('"2026-02-01"','"2026-02-30"')),'DDN-PJ033'));
test('Schedule validates end before start',()=>throws(()=>run('gantt',editModel('end: "2026-01-07"','end: "2026-01-01"')),'DDN-PJ040'));
test('Precedence contradicting supplied date rejects',()=>throws(()=>run('gantt',editModel('end: "2026-01-07"','end: "2026-01-10"')),'DDN-PJ042'));
test('Schedule uses UTC interval widths, no hidden scheduling',()=>{const r=run('gantt'),marks=r.scene.marks.filter(m=>m.start);assert.equal(marks[0].end,'2026-01-07');assert.ok(Math.abs(marks[1].w/marks[0].w-2)<1e-10);});
test('Milestones preserve zero duration',()=>{const r=run('gantt',editModel('end: "2026-01-07"','end: "2026-01-05"'));assert.equal(r.scene.marks.find(m=>m.start).w,0);});
test('Table null is visible, missing can be blank',()=>{const c=editModel('"value": 420','"value": null'),p=getPlan('record_table',c);assert.equal(p.rows[0][1],'null');});
test('Table missing policy is explicit',()=>throws(()=>run('record_table',editModel('"value": 420','"other": 420')),'DDN-PJ019'));
test('Filter uses data records and retains source identities',()=>{const p=getPlan('chart_bar',editView('chart_bar','mark:bar;','mark:bar;filter:{key:"x_record.month",op:in,value:["Jan","Mar"]};'));assert.deepEqual(p.points.map(n=>n.rawX),['Jan','Mar']);});
test('Order is deterministic',()=>{const p=getPlan('chart_bar',editView('chart_bar','mark:bar;','mark:bar;order:{key:"x_record.value",direction:desc};'));assert.deepEqual(p.points.map(n=>n.y),[810,750,690,570,510,420]);});
test('Overlapping panel spans rejected',()=>throws(()=>run('swot',editView('swot','title:"WEAKNESSES",row:0,column:1','title:"WEAKNESSES",row:0,column:0')),'DDN-PJ021'));
test('Span cannot exceed panel columns',()=>throws(()=>run('journey',editView('journey','rowspan:1,colspan:3','rowspan:1,colspan:4')),'DDN-PJ020'));
test('Unknown node kind cannot use appearance as semantics',()=>throws(()=>run('flowchart',editModel('kind: "flow.start"','kind: "flow.magic"')),'DDN050'));
test('Decision has named disjoint labels, not inferred routing order',()=>throws(()=>run('flowchart',editModel('branch: "rejected"','branch: "approved"')),'DDN-PF009'));
test('Unreachable activity rejected in closed flow profile',()=>{const c=editModel('data process {','data process {object lost "Lost" {kind:"flow.process";}');throws(()=>run('flowchart',c),'DDN-PF010');});
test('Actor does not gain attribute compartment silently',()=>throws(()=>run('usecases',editModel('kind: "uml.actor";','kind: "uml.actor"; fields {field extra;}')),'DDN-PF003'));
test('DFD store-to-external shortcut rejected',()=>{const c=editModel('data dfd {','data dfd {relation invalid @receipts -> @supplier {kind:"dfd.data";}');throws(()=>run('dfd_gane',c),'DDN-PF006');});
test('DFD process identifier must be unique',()=>throws(()=>run('dfd_gane',editModel('number:"2.0"','number:"1.0"')),'DDN-PF012'));
test('DFD styles preserve semantic identity',()=>assert.equal(run('dfd_gane').modelFingerprint,run('dfd_yourdon').modelFingerprint));
test('Cyclic generalization rejected',()=>{const c=editModel('data classes {','data classes {relation backwards @audited -> @order {kind:"uml.generalization";}');throws(()=>run('structure',c),'DDN-PF004');});
test('Requirements have stable unique text-bearing codes',()=>throws(()=>run('requirements',editModel('code:"REQ-02"','code:"REQ-01"')),'DDN-PF014'));
test('Chen does not impersonate nested document notation',()=>{const c=editModel('field name;','field name {fields {field nested;}}');throws(()=>run('chen',c),'DDN-PJ050');});
test('Data-bound views reject redacted export before producing output',()=>throws(()=>run('chart_bar',editView('chart_bar','format: @f.shared.common;','format: @f.shared.common; export {mode:redacted;}')),'DDN-PJ003'));
test('Profile graph redaction is gated, original core policy retained',()=>throws(()=>run('requirements',editView('requirements','format: @f.shared.common;','format: @f.shared.common;export {mode:redacted;}')),'DDN-PJ003'));
test('Infeasible page does not clip a matrix',()=>throws(()=>run('raci',editView('raci','format: @f.shared.common;','format: @f.shared.common;publication {size:figure;width:400px;height:400px;fit:none;overflow:error;}')),'DDN074'));
test('Scaled output respects text threshold',()=>throws(()=>run('raci',{}, {page:'a4-portrait'}),'DDN071'));
test('Vega-Lite export contains values and provenance, no data URL',()=>{const w=workspace(),v=w.exportVegaLite({entry:'views.ddn',view:'chart_bar'});assert.equal(v.data.values.length,6);assert.equal(v.data.url,undefined);assert.equal(v.usermeta.profile,'chart.basic@1');});
test('Schedule adapter reports omissions instead of fake parity',()=>assert.ok(workspace().exportVegaLite({entry:'views.ddn',view:'gantt'}).usermeta.omissions.length>=2));
test('Nonquantitative export not misidentified as chart',()=>throws(()=>workspace().exportVegaLite({entry:'views.ddn',view:'raci'}),'DDN-PJ070'));
test('Record editing updates all projections and undo restores exact source',()=>{const w=workspace(),before=w.getFiles();A.authoring.setRecordValue(w,'views.ddn','chart_bar',recordId('facts.m1'),'value',840);assert.equal(w.projectionPlan('views.ddn','chart_bar').points[0].y,840);assert.equal(w.projectionPlan('views.ddn','record_table').rows[0][1],'840');assert.ok(w.undo());assert.deepEqual(w.getFiles(),before);});
test('Invalid record editor change is atomic',()=>{const w=workspace(),before=w.getFiles();throws(()=>A.authoring.setRecordValue(w,'views.ddn','chart_bar',recordId('facts.m1'),'value','bad'),'DDN-PJ032');assert.deepEqual(w.getFiles(),before);});
test('RACI editor invalidates wrong codes atomically',()=>{const w=workspace(),before=w.getFiles();throws(()=>A.authoring.setAssignment(w,'views.ddn','raci',recordId('responsibilities.order_a'),'R'),'DDN-PJ016');assert.deepEqual(w.getFiles(),before);A.authoring.setAssignment(w,'views.ddn','raci',recordId('responsibilities.post_c'),'I');assert.equal(w.projectionPlan('views.ddn','raci').cells[2][2][0].value,'I');});
test('SVG escapes record labels and source strings',()=>{const c=editModel('"month": "Jan"','"month": "<script>alert(1)</script>"'),r=run('chart_bar',c);assert.doesNotMatch(r.svg,/<script>/);assert.match(r.svg,/&lt;script&gt;/);});

test('Projection concern can be declared once and referenced from a view',()=>{
 const t=base['views.ddn'],start=t.indexOf('view chart_bar '),end=t.indexOf('\nview ',start+1),block=t.slice(start,end),a=block.indexOf('projection {'),z=block.indexOf('\n\n}',a),props=block.slice(a+'projection '.length,z).trim();
 const named='format projected { projection shared '+props+' }\n',changed=t.slice(0,start)+named+block.slice(0,a)+'projection: @projected.shared;'+block.slice(z)+t.slice(end);
 const r=run('chart_bar',{'views.ddn':changed});assert.equal(r.scene.marks.length,6);assert.equal(r.modelFingerprint,run('chart_bar').modelFingerprint);
});
test('Projection manifest is unique and all output hashes match bytes',()=>{const mf=path.resolve(dir,'../../projections/manifest.json');if(!fs.existsSync(mf)){console.log('SKIP projections-lab manifest not imported (lean scope; see tools/README)');return;}const m=JSON.parse(fs.readFileSync(mf,'utf8'));assert.equal(m.views.length,27);assert.equal(new Set(m.views.map(v=>v.view)).size,27);for(const v of m.views){assert.ok(v.view);for(const o of v.outputs)assert.equal(sha(fs.readFileSync(path.resolve(dir,'../..',o.path))),o.sha256);}});
test('Empty bindings: declared-empty bar chart renders an empty plot, non-cartesian marks still reject',()=>{
 const empty=editView('chart_bar','records:[@m.facts.m1, @m.facts.m2, @m.facts.m3, @m.facts.m4, @m.facts.m5, @m.facts.m6]','records:[]');
 const r=run('chart_bar',empty);assert.equal(r.scene.marks.length,0);assert.match(r.svg,/intentionally empty data set/);assert.match(r.svg,/<svg/);
 throws(()=>run('chart_bar',{'views.ddn':empty['views.ddn'].replace('mark:bar','mark:pie')}),'DDN-PJ009');
});
test('Invalid projection measurement rejected',()=>throws(()=>run('chart_bar',editView('chart_bar','width:1120px','width:0px')),'DDN-PJ006'));
test('Panel span titles are measured and wrapped',()=>{const c=editView('swot','title:"STRENGTHS"','title:"THIS IS A LONG PANEL HEADING THAT MUST WRAP BEFORE ITS CONTENT IS PLACED"');const r=run('swot',c);assert.match(r.svg,/THIS IS A LONG/);assert.ok(r.scene.height>=run('swot').scene.height);});
test('Unknown RACI duplicate policy rejected',()=>throws(()=>run('raci',editView('raci','value:"x_assignment.code";','value:"x_assignment.code";duplicates:ignore;')),'DDN-PJ014'));
test('Negative bubble size rejected',()=>throws(()=>run('scatter',editModel('"count": 8','"count": -8')),'DDN-PJ035'));
test('Filtering to zero rows is not successful missing-data rendering',()=>throws(()=>run('chart_bar',editView('chart_bar','mark:bar;','mark:bar;filter:{key:"x_record.month",op:eq,value:"Never"};')),'DDN-PJ012'));
test('Input scripts containing hostile prototype properties are rejected',()=>throws(()=>run('chart_bar',editModel('"month": "Jan"','"__proto__": "bad", "month":"Jan"'))));
test('Unknown matrix relation does not silently produce blank cells',()=>throws(()=>run('matrix_general',editView('matrix_general','analysis.assignment','analysis.typo')),'DDN-PJ014'));
test('Huge panel span rejected before extent allocation',()=>throws(()=>run('swot',editView('swot','rowspan:1','rowspan:999999')),'DDN-PJ020'));
test('Finite inputs with nonfinite pie total are rejected',()=>throws(()=>run('chart_pie',{'model.ddn':base['model.ddn'].replace(/"value": \d+/g,'"value": 1e308')}),'DDN-PJ037'));
test('Finite inputs with overflowing axis span are rejected',()=>throws(()=>run('chart_bar',{'model.ddn':base['model.ddn'].replace('"value": 420','"value": -1e308').replace('"value": 570','"value": 1e308')}),'DDN-PJ032'));
test('Large but finite numeric range produces only finite SVG coordinates',()=>{const r=run('chart_bar',editModel('"value": 420','"value": 1e308'));assert.doesNotMatch(r.svg, /(?:NaN|Infinity)/);assert.ok(r.scene.marks.every(m=>[m.x,m.y,m.w,m.h].every(Number.isFinite)));});
const report={runtime:A.VERSION,scope:'Executable public source-to-SVG, data binding and negative fixtures; not external-standard certification.',passed:results.filter(t=>t.pass).length,total:results.length,results,renders};fs.mkdirSync(path.resolve(__dirname,'../tests/validation'),{recursive:true});fs.writeFileSync(path.resolve(__dirname,'../tests/validation/projections-tests.json'),JSON.stringify(report,null,2)+'\n');console.log('Projections',report.passed+'/'+report.total);if(report.passed!==report.total)process.exitCode=1;
