/* SPDX-License-Identifier: GPL-2.0-or-later */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const DDN=require('../runtime/ddn-core.js').default,Render=require('../runtime/ddn-render.js').default,Engine=require('../runtime/ddn-full.js').default;
const root=path.resolve(__dirname,'..'),reg=JSON.parse(fs.readFileSync(path.join(root,'../standard/registry/catalogue.json'),'utf8'));
const defs=fs.readFileSync(path.join(root,'../standard/registry/glyph-library.svg'),'utf8').match(/<defs>([\s\S]*?)<\/defs>/)[1];
const results=[];function test(name,fn){try{fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(e){results.push({name,status:'fail',message:e.stack});console.error('FAIL',name,e.message);}}
const base=`ddn "0.2"; module "test"; data m { object a "Alpha" {kind:table;fields {field id;}} object b "Beta" {kind:table;} relation r @a -> @b {kind:references;} } view v {data:[@m];}`;
function compile(s=base,files={},entry='main.ddn'){return DDN.build({[entry]:s,...files},entry,'v',reg).ir;}
function reject(s,code,files){assert.throws(()=>compile(s,files),e=>e.code===code);}
test('minimal data/format/view source',()=>assert.equal(compile().elements.length,2));
test('Unicode labels preserve literal content',()=>assert.equal(compile(base.replace('Alpha','Clientèle — 顧客')).elements[0].name,'Clientèle — 顧客'));
test('BOM and CRLF accepted',()=>assert.equal(compile('\uFEFF'+base.replaceAll(';',';\r\n')).relations.length,1));
test('comments are ignored semantically',()=>assert.deepEqual(DDN.semanticJSON(compile(base)),DDN.semanticJSON(compile('// header\n'+base))));
test('inline block comments',()=>assert.equal(compile(base.replace('kind:table','/* note */ kind:table')).elements.length,2));
test('missing semicolon rejected',()=>reject(base.replace('kind:table;','kind:table'),'DDN010'));
test('wrong language version rejected',()=>reject(base.replace('"0.2"','"9.0"'),'DDN012'));
test('unknown character rejected',()=>assert.throws(()=>DDN.parse(base+'$'),e=>e.code==='DDN006'));
test('unterminated comment rejected',()=>assert.throws(()=>DDN.parse(base+'/*'),e=>e.code==='DDN002'));
test('unterminated string rejected',()=>assert.throws(()=>DDN.parse(base+'"'),e=>e.code==='DDN003'));
test('lone surrogate rejected',()=>reject(base.replace('Alpha','\\uD800'),'DDN004'));
test('valid escaped surrogate pair accepted',()=>assert.equal(compile(base.replace('Alpha','\\uD83D\\uDE80')).elements[0].name,'🚀'));
test('duplicate property rejected',()=>reject(base.replace('kind:table;','kind:table;kind:table;'),'DDN011'));
test('prototype key rejected',()=>reject(base.replace('kind:table;','kind:table;__proto__:{};'),'DDN008'));
test('record duplicate key rejected',()=>reject(base.replace('kind:table;','kind:table;x_record:{a:1,a:2};'),'DDN011'));
test('duplicate declaration rejected',()=>reject(base.replace('object b','object a'),'DDN024'));
test('duplicate uid rejected',()=>reject(base.replace('kind:table;','kind:table;uid:"same";').replace('object b "Beta" {kind:table;','object b "Beta" {kind:table;uid:"same";'),'DDN026'));
test('unresolved relation reference rejected',()=>reject(base.replace('@b {kind:references','@z {kind:references'),'DDN031'));
test('unknown kind rejected',()=>reject(base.replace('kind:table;','kind:unicorn;'),'DDN050'));
test('unknown relationship rejected',()=>reject(base.replace('kind:references','kind:telepathy'),'DDN056'));
test('relation alias normalization',()=>assert.equal(compile().relations[0].kind,'ref'));
test('object alias normalization',()=>assert.equal(compile(base.replaceAll('kind:table','kind:tbl')).elements[0].kind,'table'));
test('source field endpoints resolved',()=>assert.equal(compile(base.replace('relation r @a','relation r @a.id')).relations[0].from.member,'test::m.a.id'));
test('explicit stable uid supported',()=>assert.equal(compile(base.replace('kind:table;','kind:table;uid:"urn:a";')).elements[0].id,'urn:a'));
test('view must reference data block',()=>reject(base.replace('data:[@m]','data:[@m.a]'),'DDN041'));
test('unknown view option rejected',()=>reject(base.replace('data:[@m];','data:[@m];theem:dark;'),'DDN033'));
test('undeclared view group rejected',()=>reject(base.replace('data:[@m];','data:[@m];mystery {x:1;}'),'DDN900'));
test('nested field syntax yields stable child identity',()=>assert.equal(compile(base.replace('field id;','field id {fields {field nested;}}')).elements[0].fields[1].id,'test::m.a.id.nested'));
test('only relations accept endpoints',()=>reject(base.replace('object b "Beta"','object b "Beta" @a -> @a'),'DDN055'));
test('missing import rejected',()=>reject(base.replace('data m','import "missing.ddn" as x;data m'),'DDN022'));
test('workspace escape rejected',()=>reject(base.replace('data m','import "../outside.ddn" as x;data m'),'DDN020'));
test('remote import rejected',()=>reject(base.replace('data m','import "https://invalid.example/a" as x;data m'),'DDN020'));
test('cyclic imports rejected',()=>reject(base.replace('data m','import "b.ddn" as b;data m'),'DDN021',{'b.ddn':'ddn "0.2";module "b";import "main.ddn" as a;'}));
test('import aliases resolve without identity mutation',()=>{const lib='ddn "0.2";module "lib";data m {object a;}';const s='ddn "0.2";module "main";import "lib.ddn" as lib;view v {data:[@lib.m];}';assert.equal(compile(s,{'lib.ddn':lib}).elements[0].id,'lib::m.a');});
test('explicit states differ from string literals',()=>{const p=compile(base.replace('kind:table;','kind:table;x_a:undecided;x_b:"undecided";')).elements[0].properties;assert.deepEqual(p.x_a,{$state:'undecided'});assert.equal(p.x_b,'undecided');});
test('quantities retain units',()=>{const p=compile(base.replace('kind:table;','kind:table;x_retention:365d;')).elements[0].properties;assert.deepEqual(p.x_retention,{$quantity:365,unit:'d'});});
test('unit conversion',()=>assert.ok(Math.abs(DDN.quantity({$quantity:25.4,unit:'mm'})-96)<1e-8));
test('duration is not a length',()=>assert.throws(()=>DDN.quantity({$quantity:1,unit:'s'}),e=>e.code==='DDN032'));
test('20px font size is implemented',()=>assert.equal(compile(base.replace('data:[@m];','data:[@m];style {font_size:20px;}')).view.profiles.style.font_size.$quantity,20));
test('number labels need a legend',()=>reject(base.replace('data:[@m];','data:[@m];legend {mode:numbers;placement:none;}'),'DDN047'));
test('number labels need explicit stable assignments',()=>reject(base.replace('data:[@m];','data:[@m];legend {mode:numbers;}'),'DDN061'));
test('number assignment works',()=>assert.equal(compile(base.replace('data:[@m];','data:[@m];legend {mode:numbers;keys:{"r":7};}')).view.keys['test::m.r'],7));
test('duplicate number rejected',()=>{const s=base.replace('} view v','relation s @a -> @b {kind:flow;}} view v').replace('data:[@m];','data:[@m];legend {mode:numbers;keys:{r:7,s:7};}');reject(s,'DDN060');});
test('style changes preserve semantic hashes',()=>assert.deepEqual(DDN.semanticJSON(compile()),DDN.semanticJSON(compile(base.replace('data:[@m];','data:[@m];style {look:handDrawn;}')))));
test('hide fields preserves field identity',()=>{const ir=compile(base.replace('data:[@m];','data:[@m];display {fields:none;}'));assert.equal(ir.elements[0].fields[0].id,'test::m.a.id');});
test('unsafe SVG label escapes',()=>{const svg=Render.render(compile(base.replace('Alpha','<script>bad</script>')),reg,defs).svg;assert.ok(!svg.includes('<script>'));assert.ok(svg.includes('&lt;script&gt;'));});
test('deterministic SVG output',()=>{const ir=compile();assert.equal(Render.render(ir,reg,defs).svg,Render.render(ir,reg,defs).svg);});
const files={};for(const f of fs.readdirSync(path.join(root,'../website/examples/basics')).filter(f=>f.endsWith('.ddn')))files['examples/'+f]=fs.readFileSync(path.join(root,'../website/examples/basics',f),'utf8');
const byView={};for(const [entry,s]of Object.entries(files).filter(([f])=>/\/\d\d-/.test(f)))for(const v of DDN.parse(s,entry).declarations.filter(x=>x.type==='view'))test('example '+path.basename(entry)+'#'+v.id,()=>{const {ir}=DDN.build(files,entry,v.id,reg);const result=Engine.render(ir,reg,defs);assert.ok(result.svg.startsWith('<?xml'));byView[path.basename(entry)+'#'+v.id]={ir,...result};});
test('look matrix shares one semantic model',()=>{const a=byView['02-elements.ddn#classic'];for(const k of ['handDrawn','neo','dark','neutral','forest'])assert.deepEqual(DDN.semanticJSON(a.ir),DDN.semanticJSON(byView['02-elements.ddn#'+k].ir));});
test('gap crossing is one geometric crossing, no added relation',()=>{const a=byView['03-routing.ddn#gap'];assert.equal(a.scene.crossings.length,1);assert.equal(a.ir.relations.length,2);});
test('round bridge same topology as gap',()=>assert.deepEqual(DDN.semanticJSON(byView['03-routing.ddn#gap'].ir),DDN.semanticJSON(byView['03-routing.ddn#bridge'].ir)));
test('square bridge same topology as gap',()=>assert.deepEqual(DDN.semanticJSON(byView['03-routing.ddn#gap'].ir),DDN.semanticJSON(byView['03-routing.ddn#square_bridge'].ir)));
test('all orthogonal example segments axis aligned',()=>{for(const x of Object.values(byView))if(x.ir.view.profiles.layout.routing==='orthogonal')for(const r of x.scene.routes)for(let i=1;i<r.points.length;i++)assert.ok(r.points[i][0]===r.points[i-1][0]||r.points[i][1]===r.points[i-1][1]);});
test('samples retain missing versus null',()=>{const n=byView['07-documents.ddn#documents'].ir.elements.find(n=>n.type==='sample');assert.equal(n.properties.rows[0][1],null);assert.deepEqual(n.properties.rows[1][1],{$missing:true});});
test('sample column width validation',()=>{const s=base.replace('} view v','sample rows {columns:[@a.id];rows:[[1,2]];}} view v');reject(s,'DDN053');});
test('sample columns must be fields',()=>{const s=base.replace('} view v','sample rows {columns:[@a];rows:[[1]];}} view v');reject(s,'DDN052');});
test('inline child preserves semantic data-id',()=>{const svg=byView['08-subdiagrams.ddn#inline'].svg;assert.ok(svg.includes('data-id="ddn.examples.subdiagrams::model.table"'));});
test('inline cycle is rejected',()=>{const s=base.replace('data:[@m];','data:[@m];subdiagram child {view:@v;mode:inline;}');reject(s,'DDN065');});
test('collapsed interface mode not falsely claimed',()=>reject(base.replace('data:[@m];','data:[@m];subdiagram child {view:@v;mode:collapsed;}'),'DDN900'));
test('invalid UTF-8 is rejected by fatal decoder',()=>assert.throws(()=>new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array([0xc3,0x28]))));

// Rendering-specific regressions: comparing file hashes alone is not enough.
const Sketch=require('../runtime/ddn-sketch.js').default;
function handIR(extra=''){return compile(base.replace('data:[@m];',`data:[@m];style {look:handDrawn;${extra}}`));}
function handRender(extra=''){return Render.render(handIR(extra),reg,defs);}
test('handDrawn has organic cubic line geometry',()=>{const s=handRender().svg;assert.ok(s.includes('data-sketch="outline"'));assert.match(s,/<path d="M[^\"]*C/);});
test('classic contains no sketch primitive groups',()=>assert.ok(!Render.render(compile(),reg,defs).svg.includes('data-sketch=')));
test('handDrawn shades interiors with optional hachures',()=>assert.ok(handRender().svg.includes('data-sketch-hachure="true"')));
test('handDrawn hachure false removes shading only',()=>{const s=handRender('hachure:false;').svg;assert.ok(!s.includes('data-sketch-hachure'));assert.ok(s.includes('data-sketch="outline"'));});
test('roughness zero gives unperturbed outlines without hachures',()=>{const s=handRender('roughness:0;').svg;assert.ok(!s.includes('data-sketch-hachure'));assert.ok(s.includes('data-sketch="outline"'));});
test('rounded activity shell is genuinely sketched',()=>assert.ok(byView['02-elements.ddn#handDrawn'].svg.includes('data-sketch="rounded-outline"')));
test('sample grid and field separator use sketch strokes',()=>{const s=byView['02-elements.ddn#handDrawn'].svg;assert.ok((s.match(/data-sketch="line"/g)||[]).length>=12);});
test('folded note outline is genuinely sketched',()=>{const s=byView['02-elements.ddn#handDrawn'].svg;const n=s.slice(s.indexOf('data-id="ddn.examples.elements::model.note"'));assert.ok(n.slice(0,n.indexOf('data-id="ddn.examples.elements::model.example"')).includes('data-sketch="outline"'));});
test('handDrawn deterministic same seed and identity',()=>assert.equal(handRender('seed:42;').svg,handRender('seed:42;').svg));
test('changing seed changes pen paths not layout',()=>{const a=handRender('seed:42;'),b=handRender('seed:77;');assert.notEqual(a.svg,b.svg);assert.deepEqual(a.scene,b.scene);});
test('handwritten font is separately selectable',()=>assert.ok(handRender('font:handwriting;').svg.includes('Comic Neue')));
test('handDrawn geometry works with ordinary sans font',()=>{const s=handRender('font:sans;').svg;assert.ok(s.includes('data-sketch="outline"'));assert.ok(s.includes('DejaVu Sans'));});
test('new handDrawn properties preserve model semantics',()=>assert.deepEqual(DDN.semanticJSON(compile()),DDN.semanticJSON(handIR('font:handwriting;roughness:2.2;hachure:false;seed:73;'))));
test('drawing looks preserve topology; font metrics are independent',()=>{const a=byView['09-look-comparison.ddn#classic'];for(const look of ['handDrawn','neo']){const b=byView['09-look-comparison.ddn#'+look];assert.deepEqual(DDN.semanticJSON(a.ir),DDN.semanticJSON(b.ir));assert.deepEqual(a.scene.nodes.map(n=>n.id),b.scene.nodes.map(n=>n.id));assert.deepEqual(a.scene.routes.map(n=>n.id),b.scene.routes.map(n=>n.id));}});
test('neo has distinct shadow and edge accent',()=>{const a=byView['09-look-comparison.ddn#neo'].svg;assert.ok(a.includes('opacity=".14"'));assert.ok(a.includes('opacity=".68"'));assert.ok(!a.includes('data-sketch='));});
test('handDrawn gap crossing preserves topology and exact centerlines',()=>{const a=structuredClone(byView['03-routing.ddn#gap'].ir);a.view.profiles.style.look='handDrawn';const b=Render.render(a,reg,defs);assert.deepEqual(b.scene,byView['03-routing.ddn#gap'].scene);assert.ok(b.svg.includes('mask="url(#gap-'));assert.equal(a.relations.length,2);});
test('handDrawn round bridge preserves topology',()=>{const a=structuredClone(byView['03-routing.ddn#bridge'].ir);a.view.profiles.style.look='handDrawn';assert.deepEqual(Render.render(a,reg,defs).scene,byView['03-routing.ddn#bridge'].scene);});
test('handDrawn square bridge preserves topology',()=>{const a=structuredClone(byView['03-routing.ddn#square_bridge'].ir);a.view.profiles.style.look='handDrawn';assert.deepEqual(Render.render(a,reg,defs).scene,byView['03-routing.ddn#square_bridge'].scene);});
test('solid relation pen strokes remain exact at endpoints',()=>{const s=Sketch.polyline([[10,20],[210,20]],{id:'relation',seed:8});assert.ok(s.includes('M10 20L22 20'));assert.match(s,/L210 20"/);});
test('dashed relation uses one stroke preserving dash signature',()=>{const s=Sketch.polyline([[0,0],[300,0]],{id:'dashed',dash:'2 6'});assert.equal((s.match(/<path /g)||[]).length,1);assert.ok(s.includes('stroke-dasharray="2 6"'));});
test('roughness above range rejected',()=>reject(base.replace('data:[@m];','data:[@m];style {roughness:4;}'),'DDN046'));
test('roughness negative rejected',()=>reject(base.replace('data:[@m];','data:[@m];style {roughness:-1;}'),'DDN046'));
test('roughness text rejected',()=>reject(base.replace('data:[@m];','data:[@m];style {roughness:"strong";}'),'DDN046'));
test('hachure nonboolean rejected',()=>reject(base.replace('data:[@m];','data:[@m];style {hachure:"true";}'),'DDN046'));
test('seed noninteger rejected',()=>reject(base.replace('data:[@m];','data:[@m];style {seed:2.2;}'),'DDN046'));
test('seed outside uint32 rejected',()=>reject(base.replace('data:[@m];','data:[@m];style {seed:4294967296;}'),'DDN046'));
test('unrelated primitive does not advance another shape random seed',()=>{const a=Sketch.box(0,0,270,150,{id:'customer',seed:8});Sketch.box(0,0,300,300,{id:'other',seed:8});assert.equal(a,Sketch.box(0,0,270,150,{id:'customer',seed:8}));});
test('completed SVG is vector-only with no runtime scripts or font payload',()=>{const s=handRender().svg;assert.ok(!/<script|<image|<foreignObject|@font-face|data:font|\.woff/i.test(s));assert.ok(s.includes('<text'));});
test('SVG font styles are scoped and inherited per nested root',()=>{const s=handRender().svg;assert.ok(s.includes('ddn-font-'),'scoped font class present on the root svg');assert.ok(!s.includes('text{font-family:'));});

test('gap crossing has physically interrupted path pieces',()=>{const x=byView['10-handdrawn-routing.ddn#gap'];assert.ok(x.svg.includes('data-route-pieces="2"'));});
test('crossing gap is explicit absent geometry without mask support',()=>{const x=Render.visibleRoutePieces([[0,0],[200,0]],[{point:[100,0]}]);assert.deepEqual(x,[{points:[[0,0],[93,0]],distance:0},{points:[[107,0],[200,0]],distance:107}]);});
test('crossing gap split handles reverse direction',()=>{const x=Render.visibleRoutePieces([[200,0],[0,0]],[{point:[100,0]}]);assert.deepEqual(x.map(v=>v.points),[[[200,0],[107,0]],[[93,0],[0,0]]]);});
test('legend direction and missing markers get explicit symbol font fallback',()=>assert.ok(handRender().svg.includes('<tspan font-family="DejaVu Sans, Arial, sans-serif">→</tspan>')));
const report={version:DDN.VERSION,runtime:process.version,tests:results.length,passed:results.filter(x=>x.status==='pass').length,failed:results.filter(x=>x.status==='fail').length,scope:'Executable reference subset; not full proposed conformance',results};
fs.writeFileSync(path.join(__dirname,'core-report.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({tests:report.tests,passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1;
