/* SPDX-License-Identifier: GPL-2.0-or-later. Review prototype: uses unchanged public DDN runtime. */
(() => {
'use strict';
const D=window.DDNLive, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=JSON.parse($('#sourceFiles').textContent), ws=D.createWorkspace(initial);
let entry='model.ddn',view='overview',ir=null,result=null,selected='designer.sample::model.customer',tab='meaning',left='add',mode='select',connectFrom=null,zoom=1,toastTimer,drag=null,counter=1;
let overrides={page:'content',look:'classic',theme:'default'},renderFailure=false;
const optionsByView={};const actualCommands=[];const A=D.authoring;
const templates=[['table','Table','▤','Data'],['record','Record','≡','Data'],['activity','Activity','⚙','Process'],['application','Service','▣','Systems'],['domain','Domain','◇','Meaning'],['schema','Schema','▱','Scopes'],['team','Team','♙','People'],['note','Note','▧','Evidence']];
const graph=()=>!ir||ir.view.profiles.projection?.kind==='graph';
function announce(text,error=false){const t=$('#toast');t.textContent=text;t.className='message show'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),6500);$('#status').textContent=text;}
function findSelection(){const n=ir?.elements.find(n=>n.id===selected);if(n)return{kind:'node',node:n,sourceId:n.id,name:n.name};for(const e of ir?.elements||[]){const f=e.fields?.find(f=>f.id===selected);if(f)return{kind:'field',node:e,field:f,sourceId:f.id,name:f.name};}const r=ir?.relations.find(r=>r.id===selected);if(r)return{kind:'relation',relation:r,sourceId:r.id,name:r.name};return null;}
function sourceLabel(id){for(const e of ir?.elements||[]){if(e.id===id)return e.name;const f=e.fields.find(f=>f.id===id);if(f)return e.name+'.'+f.name;}return ir?.relations.find(r=>r.id===id)?.name||id?.split('::').pop()||'';}
function selectionOwner(id){return ir?.elements.find(n=>n.id===id||n.fields.some(f=>f.id===id))?.id||null;}
function usage(id){let count=0;for(const v of ws.views(entry)){try{const p=ws.resolve(entry,v.id);if(p.view.selected.includes(selectionOwner(id)||id)||p.view.relations.includes(id))count++;}catch{}}return count;}
function sourceView(){const data=ws.getFiles();return data[entry];}
function updateSource(){if($('#sourceDrawer').classList.contains('open'))$('#sourceText').textContent=sourceView();}
function safeSVG(text){const doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror'))throw Error('Invalid SVG');doc.querySelectorAll('script,foreignObject').forEach(x=>x.remove());doc.querySelectorAll('*').forEach(e=>{for(const a of [...e.attributes]){if(/^on/i.test(a.name)||((a.name==='href'||a.name==='xlink:href')&&!a.value.startsWith('#')))e.removeAttribute(a.name);}});return document.importNode(doc.documentElement,true);}
function draw(){
 try{const next=ws.renderSync({entry,view,overrides});ir=ws.resolve(entry,view);result=next;renderFailure=false;const svg=safeSVG(next.svg);$('#paper').replaceChildren(svg);$('#paper').style.opacity='1';$('#paper').style.width=(zoom*100)+'%';
  $('#viewTag').textContent=(ir.view.profiles.projection?.kind||'graph')+' · '+(graph()?next.scene.nodes.length+' elements':next.scene.marks?.length+' source marks');
  $('#status').textContent='Live render · '+Math.round(next.milliseconds)+' ms · '+next.diagnostics.length+' reported warning(s)';
  $('#saved').textContent='Memory revision '+ws.revision;$('#undo').disabled=!ws.history().canUndo;$('#redo').disabled=!ws.history().canRedo;
  $('#canvasEyebrow').textContent=graph()?'SYNTHETIC COMMERCE MODEL / LIVE GRAPH':'SHARED PROCUREMENT MODEL / DATA-BOUND VIEW';
  $('#viewHeading').textContent={overview:'Customer orders',names:'Customer orders · compact',raci:'Responsibility assignments',chart_bar:'Supplied monthly values'}[view]||view;
  $('#viewHelp').textContent=graph()?'Select a table to edit its shared meaning. Drag to position and pin it. Connect tables or their named fields.':'Values and bindings determine geometry. Graph placement and connector tools are unavailable in this projection.';
  $('#connectTool').disabled=!graph();$('#addAuto').disabled=!graph();$('#arrangeBtn').disabled=!graph();
  if(!graph())mode='select';
  bindCanvas();updateInspector();updateLeft();highlight();updateSource();
 }catch(e){renderFailure=true;$('#paper').style.opacity='.35';announce((e.code||'RENDER')+': '+e.message,true);}
}
// Staged helper operations provide one history entry for this prototype's limited gestures.
// The production plan/impact/draft service is specified separately, not implemented here.
function transaction(label,fn){
 const before=ws.getFiles(),revision=ws.revision,t=D.createWorkspace(before);try{const value=fn(t);const after=t.getFiles();const edits=Object.keys(after).filter(f=>before[f]!==after[f]).map(f=>({file:f,start:0,end:(before[f]||'').length,text:after[f]}));if(edits.length)ws.applyEdits(edits,{expectedRevision:revision,entry,view});actualCommands.push({label,revision:ws.revision,changedFiles:edits.map(e=>e.file)});if(value?.select)selected=value.select;draw();announce(label+' · source updated · Undo available');return true;}catch(e){announce((e.code||'EDIT')+': '+e.message,true);return false;}finally{t.destroy();}}
function highlight(){const paper=$('#paper');paper.querySelectorAll('.selected,.member-selected').forEach(e=>e.classList.remove('selected','member-selected'));if(!selected){$('#selectionStatus').textContent='No selection';return;}const match=paper.querySelector('[data-id="'+CSS.escape(selected)+'"]');if(match)match.classList.add('selected');const member=paper.querySelector('[data-member="'+CSS.escape(selected)+'"]');if(member){member.classList.add('member-selected');member.closest('[data-id]')?.classList.add('selected');}$('#selectionStatus').textContent=selected?'Selected: '+sourceLabel(selected):'No selection';}
function choose(id){selected=id;$('#workspace').classList.add('inspecting');highlight();updateInspector();}
function setTab(t){tab=t;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));updateInspector();}
function setView(v){optionsByView[entry+'#'+view]={...overrides};view=v;entry=['raci','chart_bar'].includes(v)?'projections/views.ddn':'model.ddn';overrides=optionsByView[entry+'#'+view]||{page:'content',look:'classic',theme:'default'};selected=entry==='model.ddn'?'designer.sample::model.customer':null;zoom=1;updateZoom();mode='select';$('#connectTool').classList.remove('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));draw();document.body.classList.toggle('night',overrides.theme==='night');}
function updateLeft(){
 $$('[data-left]').forEach(b=>b.classList.toggle('active',b.dataset.left===left));const pane=$('#leftBody');
 if(left==='add'){
 pane.innerHTML='<input id="paletteSearch" placeholder="Find an object…" aria-label="Find a starter object"><div class="sectionlabel">Common starters <span class="countbadge">8</span></div><div class="palette">'+templates.map(([k,n,g])=>`<button draggable="true" data-add="${k}" title="Click to add automatically, or drag onto the canvas"><span class="glyph">${g}</span><span>${n}</span></button>`).join('')+'</div><div class="lefttip">One meaningful object, then options.<br><br>Click = automatic placement.<br>Drag = explicit location and pin.</div><div class="sectionlabel">Installed library · proposed shelf</div><div class="scope-list"><button data-story="library">Data structures <span class="count">Core + profiles</span></button><button data-story="library">Process & interactions</button><button data-story="library">Systems & locations</button><button data-story="library">People & control</button><button data-story="library">Analysis & reports</button></div><p class="small muted" style="margin-top:15px">This prototype exposes eight starters. The specification maps all 188 installed kinds.</p>';
 pane.querySelectorAll('[data-add]').forEach(b=>{b.disabled=!graph();b.onclick=()=>addNode(b.dataset.add);b.ondragstart=e=>{e.dataTransfer.setData('application/x-ddn-kind',b.dataset.add);e.dataTransfer.effectAllowed='copy';};});
 $('#paletteSearch').oninput=e=>{pane.querySelectorAll('[data-add]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(e.target.value.toLowerCase()));};pane.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>story(b.dataset.story));
 }else if(left==='model'){
 pane.innerHTML='<div class="row"><span class="tag teal">SHARED DEFINITIONS</span></div><p class="help small muted" style="margin-top:10px">Select a definition. This list is a keyboard alternative to the canvas.</p>'+ir.elements.filter(n=>ir.view.selected.includes(n.id)||!graph()).slice(0,35).map(n=>`<button class="model-item" data-select="${esc(n.id)}">${esc(n.name)} <span class="id">${esc(n.kind)} · ${esc(n.source?.file||'source')}</span></button>`).join('');pane.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>choose(b.dataset.select));
 }else{pane.innerHTML='<div class="tag">ONE WORKSPACE · SHARED SOURCE</div>'+['overview','names','raci','chart_bar'].map(v=>`<button class="model-item ${v===view?'active':''}" data-open-view="${v}" style="margin-top:12px">${({overview:'Structure',names:'Compact',raci:'Responsibilities',chart_bar:'Report'})[v]}<span class="id">${v==='overview'||v==='names'?'model.ddn':'projections/views.ddn'}</span></button>`).join('')+'<div class="lefttip">Changing a name edits a definition.<br><br>Changing “show fields” edits the appearance of this view.</div>';pane.querySelectorAll('[data-open-view]').forEach(b=>b.onclick=()=>setView(b.dataset.openView));}
}
function selectControl(id,label,values,current){return `<label for="${id}">${label}</label><select id="${id}">`+values.map(([v,l])=>`<option value="${v}" ${v===current?'selected':''}>${l}</option>`).join('')+'</select>';}
function updateInspector(){const sel=findSelection(),h=$('#selectionHeader'),p=$('#inspectorBody');
 if(sel){h.innerHTML=`<div class="selection-title"><span class="tag">${esc(sel.kind==='field'?'FIELD':sel.kind==='relation'?'RELATIONSHIP':sel.node.kind.toUpperCase())}</span><h2>${esc(sel.name)}</h2><p>${esc(sel.sourceId)}</p></div><div class="scope-banner">Shared definition · ${usage(sel.sourceId)} view(s) in this source entry<br>Edits to meaning affect every occurrence.</div>`;}else{h.innerHTML='<div class="selection-title"><span class="tag">VIEW SETTINGS</span><h2>'+esc($('#viewHeading').textContent)+'</h2><p>'+esc(entry+' # '+view)+'</p></div><div class="scope-banner">View configuration · shared data unchanged</div>';}
 if(tab==='view'){
 p.innerHTML='<div class="tag">LOCAL PREVIEW OVERRIDES</div>'+selectControl('lookSetting','Drawing treatment',[['classic','Standard'],['handDrawn','Hand-drawn'],['neo','Neo']],overrides.look||'classic')+selectControl('themeSetting','Palette',[['default','Light'],['night','Night · grey-blue']],overrides.theme||'default');
 if(graph())p.innerHTML+=selectControl('fieldsSetting','Field compartment',[['source','As authored'],['names','Field names'],['none','Name only']],overrides.fields||'source')+selectControl('routeSetting','Connector path',[['source','As authored'],['orthogonal','Right angles'],['curved','Curved'],['straight','Straight'],['rounded','Rounded corners']],overrides.routing||'source')+'<p class="help">A path setting changes geometry, never the meaning or endpoints.</p>';
 else if(view==='chart_bar')p.innerHTML+=selectControl('markSetting','Chart mark',[['bar','Bars'],['line','Line'],['pie','Pie'],['donut','Doughnut']],overrides.mark||'bar');
 if(sel?.kind==='node'&&graph()){const pinned=!!result.scene.layout?.pinned?.includes(sel.sourceId)||sourceView().includes('place @model.'+sel.node.local);p.innerHTML+='<hr><h3>Position</h3><p class="help">Dragging makes an explicit pin. Size alone is not a pin.</p><div class="kv"><div><label for="pinX">X · world px</label><input id="pinX" type="number" value="'+Math.round(result.scene.nodes.find(n=>n.id===sel.sourceId)?.x||0)+'"></div><div><label for="pinY">Y · world px</label><input id="pinY" type="number" value="'+Math.round(result.scene.nodes.find(n=>n.id===sel.sourceId)?.y||0)+'"></div></div><div class="row" style="margin-top:10px"><button id="pinApply" class="primary">Set pin</button><button id="unpinApply">Make automatic</button></div>';
 $('#pinApply').onclick=()=>transaction('Set this view position',t=>A.pin(t,entry,view,sel.sourceId,Number($('#pinX').value),Number($('#pinY').value)));$('#unpinApply').onclick=()=>transaction('Release source pin',t=>A.unpin(t,entry,view,sel.sourceId));}
 p.innerHTML+='<hr><p class="help">Look and palette use live renderer overrides in this prototype. Production source-write and inherited/reset rules are specified separately.</p><button id="resetStyle" class="wide">Reset this preview</button>';
 const change=(id,key)=>{const el=$('#'+id);if(el)el.onchange=()=>{overrides[key]=el.value;document.body.classList.toggle('night',overrides.theme==='night');draw();};};change('lookSetting','look');change('themeSetting','theme');change('fieldsSetting','fields');change('routeSetting','routing');change('markSetting','mark');$('#resetStyle').onclick=()=>{overrides={page:'content',look:'classic',theme:'default'};document.body.classList.remove('night');draw();};
 // Rebind position actions after innerHTML append recreated them.
 if($('#pinApply')){$('#pinApply').onclick=()=>transaction('Set this view position',t=>A.pin(t,entry,view,sel.sourceId,Number($('#pinX').value),Number($('#pinY').value)));$('#unpinApply').onclick=()=>transaction('Release source pin',t=>A.unpin(t,entry,view,sel.sourceId));}return;
 }
 if(tab==='details'){
 p.innerHTML='<div class="sectionlabel" style="margin-top:0">Details on demand</div><p class="help">Required properties appear in Meaning. Specialized implementation, evidence and scope stay discoverable here.</p>'+(sel?'<label>Source identity</label><div class="subtle"><code>'+esc(sel.sourceId)+'</code></div><label>Applicable groups</label><div class="control-stack"><button data-story="properties">Domain & representation</button><button data-story="properties">Scope & ownership</button><button data-story="properties">Constraints & evidence</button></div>':'<div class="notice">The projection determines which operations are meaningful. A record value is not a freehand position.</div>')+'<hr><h3>Current render diagnostics</h3>'+result.diagnostics.slice(0,5).map(d=>'<p class="help"><strong>'+esc(d.code)+'</strong><br>'+esc(d.message)+'</p>').join('')+'<button id="inspectSource" class="wide">Inspect actual source</button><p class="help">Advanced group screens are design proposals, not implemented specialized property editors.</p>';p.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>story(b.dataset.story));$('#inspectSource').onclick=openSource;return;
 }
 if(!graph()){
 p.innerHTML='<div class="notice">Data-bound projection. Moving a mark must not change a number, date, assignment, or scale.</div>'+(view==='raci'?'<h3>Responsibility matrix</h3><label>Rows</label><div class="subtle">Order · Receive · Post</div><label>Columns</label><div class="subtle">Buyer · Manager · Warehouse · Controller</div><label>Cell meaning</label><div class="subtle">Shared assignment / x_assignment.code</div><p class="help">Select a cell to inspect its source. The production assignment editor is described in the specification.</p>':'<h3>Supplied values</h3><label>Source</label><div class="subtle">m.facts · six synthetic records</div><label>Category</label><div class="subtle">x_record.month</div><label>Value</label><div class="subtle">x_record.value · CAD</div><p class="help">Changing the chart mark is live under This view. Binding wizards are specified, not implemented in this prototype.</p>')+'<button id="projectedSource" class="wide">View source bindings</button>';$('#projectedSource').onclick=openSource;return;
 }
 if(!sel){p.innerHTML='<h3>Select an object or relation</h3><p class="help">Choose a palette starter to insert. Use Model for keyboard selection. All new objects are synthetic local design definitions.</p>';return;}
 p.innerHTML='<label for="nameEdit">'+(sel.kind==='field'?'Field label':'Name')+'</label><input id="nameEdit" value="'+esc(sel.name)+'"><div class="row" style="margin-top:8px"><button id="applyName" class="primary">Apply label</button><button id="moreReview">Used in views…</button></div><p class="help">Changes the display label, not the stable identifier.</p>';
 if(sel.kind==='node'){
 p.innerHTML+='<label>Type</label><div class="row"><input value="'+esc(sel.node.kind)+'" readonly aria-label="Semantic kind"><button id="convertBtn">Change…</button></div><p class="help">A type conversion can change meaning. A visual look does not.</p>';
 if(['table','view','record','domain','collection'].includes(sel.node.kind)){
 p.innerHTML+='<label>Fields <span class="muted">'+sel.node.fields.length+'</span></label><div class="fieldlist">'+sel.node.fields.map(f=>`<div class="fieldrow" data-field="${esc(f.id)}"><code>${esc(f.name)}</code><button data-start="${esc(f.id)}" title="Connect this field">↗</button></div>`).join('')+'</div><div class="row" style="margin-top:8px"><input id="newField" placeholder="new_field" aria-label="New field identifier"><button id="addField">＋</button></div><p class="help">Start with names. No datatype is required.</p>';
 }
 p.innerHTML+='<hr><div class="row wrap"><button id="connectSelected">Connect…</button><button id="hideSelected">Remove from view</button></div><p class="help">Remove from view retains the shared definition.</p>';
 }else if(sel.kind==='field'){
 p.innerHTML+='<label>Owner</label><div class="subtle">'+esc(sel.node.name)+'</div><label>Meaning / domain</label><button class="wide" data-story="properties">Choose a domain… <span class="tag amber">DESIGN</span></button><p class="help">Prototype only edits the label and connects this field. Domain/type/key editing is specified in the descriptor contract.</p><button id="connectSelected" class="wide primary">Connect this field</button><button id="selectParent" class="wide">Back to '+esc(sel.node.name)+'</button>';
 }else{
 const r=sel.relation;const end=e=>e.field||e.member||e.port||e.element;
 p.innerHTML+='<label>Meaning</label><div class="subtle">'+esc(r.kind)+'</div><label>From</label><div class="endpoint-card">'+esc(sourceLabel(end(r.from)))+'</div><label>To</label><div class="endpoint-card">'+esc(sourceLabel(end(r.to)))+'</div><p class="help">Field identity and visual anchor are separate. Reconnection needs its own reviewed source transaction.</p><button id="reconnectReview" class="wide">Review reconnection design…</button>';
 }
 $('#applyName').onclick=()=>transaction('Rename shared label',t=>A.setLabel(t,entry,view,sel.sourceId,$('#nameEdit').value));$('#nameEdit').onkeydown=e=>{if(e.key==='Enter')$('#applyName').click();if(e.key==='Escape')e.target.value=sel.name;};$('#moreReview').onclick=()=>story('impact');if($('#convertBtn'))$('#convertBtn').onclick=()=>story('conversion');
 p.querySelectorAll('[data-field]').forEach(x=>x.onclick=e=>{if(!e.target.closest('button'))choose(x.dataset.field);});p.querySelectorAll('[data-start]').forEach(x=>x.onclick=()=>beginConnect(x.dataset.start));p.querySelectorAll('[data-story]').forEach(x=>x.onclick=()=>story(x.dataset.story));
 if($('#addField'))$('#addField').onclick=()=>{const id=$('#newField').value;transaction('Add untyped field',t=>A.addField(t,entry,view,sel.sourceId,{id}));};
 if($('#connectSelected'))$('#connectSelected').onclick=()=>beginConnect(sel.sourceId);if($('#selectParent'))$('#selectParent').onclick=()=>choose(sel.node.id);if($('#hideSelected'))$('#hideSelected').onclick=()=>{transaction('Remove appearance, retain definition',t=>A.hide(t,entry,view,sel.sourceId));selected=null;updateInspector();};if($('#reconnectReview'))$('#reconnectReview').onclick=()=>story('connection');
}
function addNode(kind,at){if(!graph())return;const name=templates.find(x=>x[0]===kind)?.[1]||kind,id='new_'+kind+'_'+counter++;
 transaction('Add '+name+(at?' at chosen position':' automatically'),t=>{A.addElement(t,entry,view,{id,name:'New '+name,kind});const n=t.resolve(entry,view).elements.find(n=>n.local===id);if(at)A.pin(t,entry,view,n.id,at.x,at.y);return{select:n.id};});
}
function worldPoint(e){const g=$('#paper svg #drawing')||$('#paper svg');if(!g)return null;const m=g.getScreenCTM();if(!m)return null;return new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());}
function bindCanvas(){
 $('#paper').onpointerdown=e=>{
  if(e.button!==0||!graph())return;const member=e.target.closest('[data-member]'),el=e.target.closest('.ddn-node[data-id]'),edge=e.target.closest('.ddn-edge[data-id]');const id=member?.dataset.member||el?.dataset.id||edge?.dataset.id;
  if(mode==='connect'&&id){e.preventDefault();if(!connectFrom){connectFrom=id;announce('From '+sourceLabel(id)+'. Select the destination.');}else showConnection(connectFrom,id);return;}
  if(id)choose(id);if(!el||member||mode!=='select')return;const n=result.scene.nodes.find(n=>n.id===el.dataset.id);if(!n)return;const point=worldPoint(e);drag={el,id:n.id,x:n.x,y:n.y,start:point,pointer:e.pointerId,moved:false};el.setPointerCapture(e.pointerId);
 };
 $('#paper').onpointermove=e=>{if(!drag||e.pointerId!==drag.pointer)return;const p=worldPoint(e);const dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(Math.abs(dx)+Math.abs(dy)<5&&!drag.moved)return;drag.moved=true;drag.dx=dx;drag.dy=dy;drag.el.setAttribute('transform','translate('+dx+' '+dy+')');};
 $('#paper').onpointerup=e=>{if(!drag)return;const d=drag;drag=null;try{d.el.releasePointerCapture(e.pointerId);}catch{}if(d.moved)transaction('Move and pin '+sourceLabel(d.id),t=>A.pin(t,entry,view,d.id,d.x+d.dx,d.y+d.dy));};
 $('#paper').onpointercancel=()=>{if(drag){drag.el.removeAttribute('transform');drag=null;announce('Move cancelled; source unchanged.');}};
 $('#paper').onclick=e=>{if(!graph()){const m=e.target.closest('[data-id],[data-source]');if(m){const id=m.getAttribute('data-id')||m.getAttribute('data-source');if(id){selected=id;updateInspector();announce('Source-bound mark selected. Binding editor is specified; source is inspectable.');}}}};
}
$('#viewport').ondragover=e=>{if(graph()){e.preventDefault();e.dataTransfer.dropEffect='copy';}};
$('#viewport').ondrop=e=>{const kind=e.dataTransfer.getData('application/x-ddn-kind');if(!templates.some(t=>t[0]===kind))return;e.preventDefault();const p=worldPoint(e)||{x:0,y:0};addNode(kind,{x:p.x-80,y:p.y-25});};
function modal(title,body,actions,live=true){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;$('#dialogTag').textContent=live?'LIVE ACTION · REAL SOURCE':'PROPOSED WORKFLOW · NOT EXECUTED';$('#dialogTag').className='tag '+(live?'teal':'amber');$('#dialogActions').innerHTML='';for(const a of actions){const b=document.createElement('button');b.textContent=a.label;b.className=a.primary?'primary':'';b.onclick=a.action;$('#dialogActions').appendChild(b);}$('#dialog').showModal();}
function closeModal(){$('#dialog').close();$('#reviewScreen').value='live';}
function endpointOptions(current){return ir.elements.filter(n=>ir.view.selected.includes(n.id)).map(n=>`<optgroup label="${esc(n.name)}"><option value="${esc(n.id)}" ${current===n.id?'selected':''}>${esc(n.name)} · object</option>`+(n.fields||[]).map(f=>`<option value="${esc(f.id)}" ${current===f.id?'selected':''}>${esc(n.name+'.'+f.name)} · field</option>`).join('')+'</optgroup>').join('');}
function beginConnect(from){connectFrom=from;mode='connect';$('#selectTool').classList.remove('active');$('#connectTool').classList.add('active');announce('Choose a target in the diagram, or select it in the connection sheet.');showConnection(from,null);}
function showConnection(from,to){mode='select';connectFrom=null;$('#connectTool').classList.remove('active');$('#selectTool').classList.add('active');const fallback=ir.elements.find(n=>n.id!==selectionOwner(from))?.id;
 modal('Create a relationship','<p>Choose meaning independently of line shape. The current validator checks the resulting endpoints.</p><label for="connectFrom">From</label><select id="connectFrom">'+endpointOptions(from)+'</select><div class="preview-arrow">↓</div><label for="connectTo">To</label><select id="connectTo">'+endpointOptions(to||fallback)+'</select>'+selectControl('relationMeaning','Relationship meaning',[['ref','References'],['assoc','Associated with'],['flow','Data flows to'],['depends','Depends on']],'ref')+'<label for="relationLabel">Label</label><input id="relationLabel" value="New reference"><div class="notice">Prototype creation uses the existing helper’s local <code>editor_data</code> block. Production shared destination and impact selection are required in the specification.</div>',[{label:'Cancel',action:closeModal},{label:'Create relationship',primary:true,action:()=>{const from=$('#connectFrom').value,to=$('#connectTo').value,kind=$('#relationMeaning').value,name=$('#relationLabel').value;const ok=transaction('Create semantic relationship',t=>{A.addRelation(t,entry,view,{id:'connection_'+counter++,name,kind,from,to});});if(ok)closeModal();}}]);}
function story(type){const sel=findSelection(),n=sel?.name||'Customer';const sections={
 conversion:['Change the type, not just the shape',`<p>Review design for converting <strong>${esc(n)}</strong>. This screen does not perform a conversion.</p><div class="row"><div class="endpoint-card">Table</div><strong>→</strong><div class="endpoint-card">SQL view</div></div><div class="storyline"><h3>Keep</h3><p>Stable identity, compatible fields, names and descriptions.</p><h3>Review before converting</h3><p>Primary-key enforcement, storage placement, write behavior, implementation dependencies and all affected views.</p><h3>3 affected views</h3><p>Structure · Deployment · SQL dependency. The production impact resolver must calculate this list; these are illustrative labels.</p></div><div class="notice">Conversion cannot silently retain incompatible metadata or discard a property. The command planner returns a source diff and requires confirmation.</div>`],
 draft:['Build incomplete diagrams safely','<p>A user must be able to place Start before End. The current strict flowchart validator rejects that intermediate diagram.</p><div class="fake-sheet"><span class="tag amber">DRAFT OBLIGATIONS</span><p>Start has no outgoing step.</p><p>At least one End is required before review/export.</p><p>Untyped connection requires a meaning.</p></div><p>Proposed behavior: show repairable draft objects, record incomplete obligations separately from unsafe syntax, preserve source, and keep reviewed publication strict.</p><div class="notice">Draft-state validation and rendering are new core requirements. This prototype does not bypass existing validators.</div>'],
 connection:['Relation identity versus visual attachment',`<p>The semantic endpoints remain <strong>Journal Line.journal</strong> and <strong>Journal Header.id</strong>.</p><div class="fake-sheet"><h3>Meaning</h3><p>References · enforcement undecided</p><h3>This view</h3><p>Curved · automatic side/anchor · numbered key</p></div><p>A control point can move along a legal outline. Reconnecting to a different field is a separate meaning-changing command with impact preview.</p><div class="notice">The fixed endpoint-ordering renderer is used by this prototype. This screen specifies a future reconnection/anchor editor.</div>`],
 export:['Publication and source downloads','<p>Source workspaces are internal design material. A hidden salary field may remain in a source archive.</p><div class="control-stack"><button disabled>Download source workspace — authority required</button><button disabled>Export current SVG — display selection only</button><button disabled>Authorized publication — validated allowlist policy</button></div><p>These disabled buttons document production choices. Use Download in the real toolbar for the synthetic prototype files.</p><div class="notice">Unsupported redacted projections must fail closed. No “ignore validation” option should be offered.</div>'],
 impact:['Shared-change review',`<p>Editing <strong>${esc(n)}</strong> changes the definition. Moving it normally changes only an appearance in this view.</p><div class="fake-sheet"><h3>Change preview</h3><p>Old label → proposed label</p><p>Definition, fields, references and all matching source ranges are retained.</p></div><h3>Impact requirements</h3><p>Resolve direct and transitive dependent views, show invalidated rules and publication constraints, and commit one source transaction against the checked revision.</p><div class="notice">A complete cross-view impact planner is a specified addition, not implemented by this screen. The live name editor above updates actual shared source.</div>`],
 properties:['Progressive property system','<p>Keep six or fewer common controls visible; make specialized properties discoverable through typed groups and search.</p><div class="fake-sheet"><h3>Meaning</h3><p>Name · Type · Fields · Description · Status</p><h3>This view</h3><p>Compartments · Icons/text · Pin · Route</p><h3>Details</h3><p>Domains · Constraints · Ownership · Evidence</p></div><p>Each descriptor declares scope, value states, source adapter, applicability, reset behavior and validation. Unset, undecided and false are not the same value.</p>'],
 library:['188 kinds without 188 default buttons','<p>The complete registry is mapped in <code>contracts/kind-ui-map.json</code>. The default shelf uses eight task groups and relevant templates.</p><div class="fake-sheet"><h3>Data</h3><p>Table · View · Record · Collection</p><h3>Process</h3><p>Activity · Decision · Start/End</p><h3>Scopes</h3><p>Namespace · Location · Team boundary</p></div><p>A template combines a registered semantic kind, legal options, content sections, default recipe and a small contextual inspector. It does not replace every kind with a generic rectangle.</p>']};
 const [title,body]=sections[type]||sections.impact;modal(title,body,[{label:'Return to live prototype',primary:true,action:closeModal}],false);
}
function arrange(){modal('Arrange the unpinned elements','<p>Existing source pins remain fixed. This dialog changes the renderer’s live placement overlay, not the business model.</p>'+selectControl('layoutPick','Pattern',[['auto','Adaptive'],['fit_grid','Fit to grid'],['circular','Circular'],['radial','Radial'],['layered','Layered'],['organic','Organic']],overrides.placement||'auto')+'<div class="notice">Production selected-subgraph preview and persistent source overrides are specified separately. This prototype invokes existing whole-view patterns.</div>',[{label:'Cancel',action:closeModal},{label:'Apply to this preview',primary:true,action:()=>{overrides.placement=$('#layoutPick').value;overrides.center='pins';closeModal();draw();}}]);}
function openSource(){$('#sourceDrawer').classList.add('open');updateSource();}
function updateZoom(){$('#paper').style.width=(zoom*100)+'%';$('#zoomLabel').textContent=Math.round(zoom*100)+'%';}
$('#dialogClose').onclick=closeModal;$('#dialog').addEventListener('cancel',()=>$('#reviewScreen').value='live');
$('#sourceBtn').onclick=openSource;$('#closeSource').onclick=()=>$('#sourceDrawer').classList.remove('open');$('#reviewBtn').onclick=()=>story('impact');$('#reviewScreen').onchange=e=>{if(e.target.value!=='live')story(e.target.value);};
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('[data-left]').forEach(b=>b.onclick=()=>{left=b.dataset.left;updateLeft();});$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#undo').onclick=()=>{ws.undo();draw();announce('Undo · source restored');};$('#redo').onclick=()=>{ws.redo();draw();announce('Redo · source restored');};
$('#selectTool').onclick=()=>{mode='select';connectFrom=null;$('#selectTool').classList.add('active');$('#connectTool').classList.remove('active');announce('Select objects or fields. Drag a selected object to pin it.');};$('#connectTool').onclick=()=>{mode='connect';connectFrom=null;$('#selectTool').classList.remove('active');$('#connectTool').classList.add('active');announce('Click a source, then a destination. Escape cancels.');};
$('#fitBtn').onclick=()=>{const svg=$('#paper>svg'),v=svg?.viewBox.baseVal,port=$('#viewport');if(v?.width&&v?.height){const availableW=port.clientWidth-48,availableH=port.clientHeight-75;zoom=Math.min(1,(availableH/v.height)/(availableW/v.width));}else zoom=1;updateZoom();};$('#zoomIn').onclick=()=>{zoom=Math.min(2,zoom+.2);updateZoom();};$('#zoomOut').onclick=()=>{zoom=Math.max(.4,zoom-.2);updateZoom();};$('#arrangeBtn').onclick=arrange;$('#addAuto').onclick=()=>addNode('table');
$('#exportBtn').onclick=()=>{modal('Download the live design','<p>The files below contain the current synthetic design. They are not a production-authorized export.</p><div class="endpoint-card"><strong>'+esc(entry)+'</strong><p>Current source file. Its imports still require their files.</p></div><p>The workspace ZIP includes all supporting DDN sources. Its file format can be opened in the existing Studio.</p>',[{label:'Current DDN',action:()=>D.io.download(entry.split('/').pop(),ws.getFiles()[entry],'text/plain;charset=utf-8')},{label:'Workspace ZIP',primary:true,action:()=>D.io.download('designer-prototype-workspace.zip',D.io.toZIP(ws.snapshot(entry,view,overrides)),'application/zip')},{label:'Current SVG',action:()=>{if(renderFailure)return announce('Current render is invalid; export blocked.',true);D.io.download('designer-prototype.svg',result.svg,'image/svg+xml');}}]);};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){connectFrom=null;mode='select';if(drag){drag.el.removeAttribute('transform');drag=null;}$('#connectTool').classList.remove('active');$('#selectTool').classList.add('active');}if(e.target.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?ws.redo():ws.undo();draw();}if(e.key==='Delete'&&graph()&&findSelection()?.kind==='node')$('#hideSelected')?.click();});
window.DesignerPrototype={workspace:ws,getState:()=>({entry,view,selected,tab,result,commands:actualCommands,overrides}),select:choose,setView,story,draw,transaction};
draw();
})();
