// SPDX-License-Identifier: GPL-2.0-or-later.
// Generates designer/prototype/kind-ui-map.js and relation-ui-map.js as UMD
// wrappers around the contracts, so file:// pages load them via <script src>
// without fetch(). Node, no dependencies. Deterministic: same contracts in,
// same bytes out.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

export function buildUIMaps(outDir = here) {
  const jobs = [
    { contract: 'kind-ui-map.json', global: 'DDNKindUIMap', out: 'kind-ui-map.js' },
    { contract: 'relation-ui-map.json', global: 'DDNRelationUIMap', out: 'relation-ui-map.js' },
  ];
  const written = {};
  for (const job of jobs) {
    const raw = readFileSync(join(here, '..', 'contracts', job.contract), 'utf8');
    const data = JSON.parse(raw);
    const json = JSON.stringify(data);
    if (json.includes('</script>')) throw new Error(job.contract + ' must not contain a script-closing tag');
    const body = '/* Generated by build-ui-maps.mjs — do not edit. Source: designer/contracts/' + job.contract + ' */\n'
      + '(function(root,factory){const map=factory();if(typeof module===\'object\'&&module.exports)module.exports=map;else root.' + job.global + '=map;})(typeof globalThis!==\'undefined\'?globalThis:this,function(){\'use strict\';return '
      + json + ';\n});\n';
    writeFileSync(join(outDir, job.out), body);
    written[job.out] = body;
  }
  return written;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const outIdx = process.argv.indexOf('--out');
  const outDir = outIdx > -1 ? process.argv[outIdx + 1] : here;
  const written = buildUIMaps(outDir);
  console.log('build-ui-maps: wrote ' + Object.keys(written).join(', ') + ' to ' + outDir);
}
