/* SPDX-License-Identifier: GPL-2.0-or-later. Accessible, virtual SVG text windows. */
import {optionalNamespace} from '../../runtime/ddn-module-registry.js';
export function installNoteScroll(svg,scene,offsets){const content=optionalNamespace('DDNContent');if(!content)return;const notes=new Map((scene.nodes||[]).filter(n=>n.noteViewport).map(n=>[n.id,n.noteViewport]));for(const group of svg.querySelectorAll('.ddn-note-window')){const id=group.getAttribute('data-note-id'),note=notes.get(id);if(!note)continue;let [x,y]=offsets.get(id)||[0,0];const maxX=Math.max(0,note.width-note.viewportWidth),maxY=Math.max(0,note.height-note.viewportHeight),body=group.querySelector('.ddn-note-content');
 const update=()=>{x=Math.max(0,Math.min(x,maxX));y=Math.max(0,Math.min(y,maxY));body.innerHTML=content.windowSVG(note,x,y);offsets.set(id,[x,y]);while(offsets.size>512)offsets.delete(offsets.keys().next().value);for(const bar of group.querySelectorAll('.ddn-note-scroll')){const v=bar.dataset.axis==='vertical',pos=v?y:x,max=v?maxY:maxX,len=v?note.viewportHeight:note.viewportWidth,thumb=bar.querySelector('.ddn-note-thumb'),tl=Number(thumb.getAttribute(v?'height':'width'));thumb.setAttribute(v?'y':'x',String(max?pos/max*(len-tl):0));bar.setAttribute('aria-valuenow',String(Math.round(pos)));}};
 group.addEventListener('wheel',e=>{if(!maxX&&!maxY)return;e.preventDefault();e.stopPropagation();const scale=Math.max(.01,Math.hypot(group.getScreenCTM()?.a||1,group.getScreenCTM()?.b||0));x+=(e.shiftKey?e.deltaY:e.deltaX)/scale;y+=(e.shiftKey?0:e.deltaY)/scale;update();},{passive:false});
 group.addEventListener('keydown',e=>{let used=true;switch(e.key){case'ArrowDown':y+=24;break;case'ArrowUp':y-=24;break;case'ArrowRight':x+=24;break;case'ArrowLeft':x-=24;break;case'PageDown':y+=note.viewportHeight;break;case'PageUp':y-=note.viewportHeight;break;case'Home':x=0;y=0;break;case'End':y=maxY;break;default:used=false;}if(used){e.preventDefault();e.stopPropagation();update();}});
 for(const bar of group.querySelectorAll('.ddn-note-scroll')){bar.style.cursor='pointer';const v=bar.dataset.axis==='vertical',length=v?note.viewportHeight:note.viewportWidth,max=v?maxY:maxX,thumb=bar.querySelector('.ddn-note-thumb');let drag=null;const local=e=>new DOMPoint(e.clientX,e.clientY).matrixTransform(group.getScreenCTM().inverse());
 bar.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();bar.focus();const pos=local(e),coord=v?pos.y:pos.x,tl=Number(thumb.getAttribute(v?'height':'width'));if(e.target===thumb)drag={at:coord,start:v?y:x};else{const next=Math.max(0,Math.min(1,(coord-tl/2)/Math.max(1,length-tl)))*max;if(v)y=next;else x=next;drag={at:coord,start:next};update();}bar.setPointerCapture(e.pointerId);});
 bar.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();e.stopPropagation();const pos=local(e),tl=Number(thumb.getAttribute(v?'height':'width')),next=drag.start+((v?pos.y:pos.x)-drag.at)/Math.max(1,length-tl)*max;if(v)y=next;else x=next;update();});const end=e=>{if(drag){drag=null;e.stopPropagation();if(bar.hasPointerCapture(e.pointerId))bar.releasePointerCapture(e.pointerId);}};bar.addEventListener('pointerup',end);bar.addEventListener('pointercancel',end);bar.addEventListener('click',e=>e.stopPropagation());}
 update();}}
