/* SPDX-License-Identifier: GPL-2.0-or-later. Local, full-source DDN workspace editor. */
(function(){'use strict';
let selectedMatrixCell=null;
const A=DDNLive,$=id=>document.getElementById(id),all=globalThis.DDNLiveData||{files:{},catalogue:{entries:[]}};
const fresh=`ddn "0.5";\nmodule "my.design";\n\n// Definitions are shared; layout and appearance belong to the view.\ndata model {\n    object client "Client application" { kind: application; }\n    object service "Order service" { kind: application; }\n    object orders "Orders" {\n        kind: table;\n        fields { field order_id; field customer_id; field status; }\n    }\n    relation request "Submit order" @client -> @service { kind: flow; }\n    relation write "Persist accepted order" @service -> @orders { kind: flow; }\n}\n\nview overview "Order processing" {\n    data: [@model];\n    layout { algorithm: auto; routing: curved; crossings: gap; }\n    style { look: classic; theme: night; }\n    publication { size: content; fit: none; }\n    legend { mode: tokens; placement: right; }\n}\n`;
let ws=null,diagram=null,currentFile='',entry='',view='',selected=null,lastModel=null,bufferDirty=false,timer=null,unsubscribe=null,saved={},mergeNext=false,dialogAction=null,search='';
const note=(text,error=false)=>{$('notice').textContent=text;$('notice').classList.toggle('error',error);};
function guard(fn){try{const r=fn();if(r?.catch)r.catch(error);return r;}catch(e){error(e);}}
function error(e){note((e.code?e.code+': ':'')+e.message,true);$('source-error').textContent=(e.source?e.source+': ':'')+(e.code||'ERROR')+' '+e.message;}
function closure(file){const out={},visiting=new Set();function load(n){if(visiting.has(n)||Object.hasOwn(out,n))return;if(!Object.hasOwn(all.files,n))throw new Error('Missing example dependency: '+n);visiting.add(n);out[n]=all.files[n];for(const imp of A.parse(out[n],n).imports)load(A.resolvePath(n,imp.path));visiting.delete(n);}load(file);return out;}
function dirty(){return bufferDirty||Object.entries(ws?.getFiles()||{}).some(([p,t])=>saved[p]!==t)||Object.keys(saved).some(p=>!Object.hasOwn(ws?.getFiles()||{},p));}
function updateHistory(){$('undo').disabled=!ws?.history().canUndo;$('redo').disabled=!ws?.history().canRedo;}
function filesUI(){const fs=ws.getFiles(),q=$('file-search').value.toLowerCase();$('file-count').textContent=Object.keys(fs).length;$('file-list').replaceChildren(...Object.keys(fs).sort().filter(n=>n.toLowerCase().includes(q)).map(n=>{const li=document.createElement('li'),b=document.createElement('button');b.textContent=n;b.title=n;b.className=n===currentFile?'selected':'';b.addEventListener('click',()=>guard(()=>showFile(n)));li.append(b);return li;}));$('workspace-info').textContent=`Runtime ${A.VERSION}\n${Object.keys(fs).length} files\n${Object.values(fs).reduce((n,t)=>n+t.length,0).toLocaleString()} source characters\nRevision ${ws.revision}\nAll data stays in this page's memory.`;}
function entriesUI(preferredView=view){let entries=ws.entries();if(entry&&Object.hasOwn(ws.getFiles(),entry)&&!entries.some(e=>e.file===entry)){try{ws.analyze(entry);}catch{entries.unshift({file:entry,views:view?[{id:view,name:view+' (source has errors)'}]:[]});}}$('entry').replaceChildren(...entries.map(e=>new Option(e.file,e.file)));if(!entries.some(e=>e.file===entry))entry=entries[0]?.file||'';$('entry').value=entry;const views=entries.find(e=>e.file===entry)?.views||[];view=views.some(v=>v.id===preferredView)?preferredView:views[0]?.id||'';$('view').replaceChildren(...views.map(v=>new Option(v.name,v.id)));$('view').value=view;}
function cursor(){const s=$('source'),a=s.value.slice(0,s.selectionStart),lines=a.split('\n');$('cursor-position').textContent=`Line ${lines.length}, column ${lines.at(-1).length+1}`;}
function showFile(file,range){flush();const fs=ws.getFiles();if(!Object.hasOwn(fs,file))return;currentFile=file;$('source-name').textContent=file;$('source').value=fs[file];bufferDirty=false;$('dirty').textContent='';if(range){$('source').focus();$('source').setSelectionRange(range.start,range.end);const lines=$('source').value.slice(0,range.start).split('\n').length;$('source').scrollTop=Math.max(0,(lines-4)*20);}filesUI();cursor();}
function flush(){clearTimeout(timer);if(ws&&bufferDirty&&currentFile){const file=currentFile,text=$('source').value;bufferDirty=false;ws.updateFiles({[file]:text});$('dirty').textContent='In memory · download to save';}}
function refreshModel(){try{lastModel=ws.resolve(entry,view);$('source-error').textContent='';const shown=new Set(lastModel.view.selected),items=[];for(const n of lastModel.elements)if(shown.has(n.id)){items.push(new Option(n.name+' · '+n.kind,n.id));for(const f of n.fields)items.push(new Option('  '+f.name+' · field',f.id));}for(const r of lastModel.relations)if(lastModel.view.relations.includes(r.id))items.push(new Option('↗ '+r.name+' · relation',r.id));$('outline').replaceChildren(...items);if(selected)$('outline').value=selected;}catch(e){lastModel=null;$('source-error').textContent=(e.code||'ERROR')+': '+e.message;}}
function selection(id){selected=id;refreshModel();if(!lastModel)return;let n=lastModel.elements.find(n=>n.id===id),relation=lastModel.relations.find(n=>n.id===id),field=lastModel.elements.flatMap(n=>n.fields).find(n=>n.id===id);const item=n||relation||field;if(!item)return;$('outline').value=id;$('selection-summary').textContent=`${item.name} · ${relation?'relationship':field?'field':n.kind}\n${id}`;$('inspector-controls').hidden=false;$('label-value').value=item.name;const choices=relation?A.relations:A.kinds;$('kind-value').replaceChildren(...choices.map(k=>new Option(k.label,k.id)));$('kind-value').value=item.kind||'';$('kind-value').disabled=$('set-kind').disabled=!!field;const g=diagram?.result?.scene.nodes.find(n=>n.id===id);$('position-x').value=g?.x??0;$('position-y').value=g?.y??0;for(const k of ['pin','unpin','hide'])$(k).disabled=!n||diagram?.capabilities?.graphControls===false;$('add-field').disabled=!!relation;$('delete-definition').disabled=false;
 const record=n?.properties?.x_record;$('record-edit').hidden=!record;$('assignment-edit').hidden=!relation?.properties?.x_assignment;
 if(record){$('record-key').replaceChildren(...Object.keys(record).filter(k=>record[k]===null||typeof record[k]!=='object').map(k=>new Option(k,k)));$('record-value').value=JSON.stringify(record[$('record-key').value]);}
 if(relation?.properties?.x_assignment)$('assignment-code').value=relation.properties.x_assignment.code;
 }
 $('record-key').addEventListener('change',()=>{const n=lastModel?.elements.find(n=>n.id===selected);if(n)$('record-value').value=JSON.stringify(n.properties.x_record[$('record-key').value]);});
 $('record-save').addEventListener('click',()=>guard(()=>{flush();const value=JSON.parse($('record-value').value);A.authoring.setRecordValue(ws,entry,view,selected,$('record-key').value,value);note('Shared value updated; dependent views re-render from the model.');}));
 $('assignment-save').addEventListener('click',()=>guard(()=>{flush();A.authoring.setAssignment(ws,entry,view,selected,$('assignment-code').value);note('Shared assignment updated and validated.');}));
$('matrix-cell-save').onclick=()=>guard(()=>guided(()=>{if(!selectedMatrixCell)throw new Error('Select a matrix cell');A.authoring.setMatrixCell(ws,entry,view,selectedMatrixCell.row,selectedMatrixCell.column,JSON.parse($('matrix-cell-value').value));}));
$('matrix-cell-remove').onclick=()=>guard(()=>guided(()=>{if(!selectedMatrixCell)throw new Error('Select a matrix cell');A.authoring.setMatrixCell(ws,entry,view,selectedMatrixCell.row,selectedMatrixCell.column,undefined,{remove:true});}));
function mount(overrides={},layoutState=null){selectedMatrixCell=null;$('matrix-cell-edit').hidden=true;if(diagram)diagram.destroy();diagram=null;if(!entry||!view){$('viewer').textContent='This workspace has no valid named view yet. Add one in the source editor.';return;}diagram=A.mount($('viewer'),{workspace:ws,entry,view,overrides,layoutState,title:view});diagram.setAttribute('source-hidden','');diagram.addEventListener('ddn-select',e=>guard(()=>{showFile(e.detail.source.file,e.detail.source);selection(e.detail.id);selectedMatrixCell=e.detail.childView?null:e.detail.matrix;$('matrix-cell-edit').hidden=!selectedMatrixCell;if(selectedMatrixCell){$('matrix-cell-name').textContent=selectedMatrixCell.row.split('::').at(-1)+' × '+selectedMatrixCell.column.split('::').at(-1);const plan=ws.projectionPlan(entry,view),i=plan.rows.findIndex(n=>n.id===selectedMatrixCell.row),j=plan.columns.findIndex(n=>n.id===selectedMatrixCell.column);$('matrix-cell-value').value=JSON.stringify(plan.cells[i][j][0]?.raw??(plan.encoding?.mode==='numeric'?0:'C'));}const target=$('contributors');if(target){const ids=e.detail.sourceIds||[];target.hidden=ids.length<2;target.replaceChildren(document.createTextNode(ids.length+' contributing definitions: '),...ids.map(id=>{const b=document.createElement('button');b.textContent=id.split('::').at(-1);b.onclick=()=>{selection(id);const s=A.authoring.sourceOf(ws,entry,view,id);showFile(s.file,s);};return b;}));}}));diagram.addEventListener('ddn-render',()=>{refreshModel();if(selected)selection(selected);$('drag-mode').disabled=diagram.capabilities.graphControls===false;if($('drag-mode').disabled)$('drag-mode').checked=false;attachDrag();});diagram.addEventListener('ddn-error',e=>{$('source-error').textContent=e.detail.code+': '+e.detail.message;});diagram.addEventListener('ddn-navigate',e=>guard(()=>{const target=e.detail.view||e.detail.target;for(const en of ws.entries()){const doc=ws.analyze(en.file);let vv=null;for(const sec of doc.sections){vv=sec.declarations.find(n=>n.type==='view'&&(sec.module+'::'+n.id===target||n.id===target));if(vv)break;}if(vv){entry=en.file;view=vv.id;entriesUI(view);mount();return;}}note('Linked view not present in this workspace: '+target,true);}));refreshModel();}
function load(files,e,v,overrides={},state=null){if(diagram)diagram.destroy();unsubscribe?.();ws?.destroy();ws=A.createWorkspace(files);currentFile='';bufferDirty=false;selected=null;lastModel=null;entry=e||'';view=v||'';saved={...files};unsubscribe=ws.subscribe(()=>{filesUI();updateHistory();refreshModel();});entriesUI(view);showFile(Object.hasOwn(files,entry)?entry:Object.keys(files)[0]);mount(overrides,state);$('inspector-controls').hidden=true;updateHistory();note(`Opened ${Object.keys(files).length} DDN file(s). No files have been sent to a server.`);}
function loadExample(index){const ex=all.catalogue.entries[index];if(!ex)throw new Error('Example not found.');if(dirty()&&!confirm('Replace this workspace? Download unsaved changes first.'))return;load(closure(ex.entry),ex.entry,ex.view);}
function snapshot(){flush();return ws.snapshot(entry,view,diagram?.getState().overrides||{},diagram?.result?.scene.layout?.autoPlace===false?diagram._layoutState:null);}
function saveFile(){flush();A.io.download(currentFile.split('/').at(-1),ws.getFiles()[currentFile]);saved[currentFile]=ws.getFiles()[currentFile];note('Downloaded '+currentFile+'. Imports remain separate; use workspace ZIP for the complete design.');}
function saveWorkspace(zip){const s=snapshot();if(zip)A.io.download('design.ddn-workspace.zip',A.io.toZIP(s),'application/zip');else A.io.download('design.ddn-workspace.json',A.io.toJSON(s),'application/json');saved=ws.getFiles();note('Downloaded the complete source workspace, including shared files and view settings.');}
async function openFiles(input,directory=false){const result=await A.io.open(input,{directory});if(mergeNext){flush();const old=ws.getFiles(),collisions=Object.keys(result.files).filter(f=>Object.hasOwn(old,f));if(collisions.length&&!confirm('Replace these existing source files?\n'+collisions.join('\n')))return;ws.updateFiles(result.files);entriesUI(view);showFile(Object.keys(result.files)[0]);mount(diagram?.options||{});note('Added '+Object.keys(result.files).length+' source file(s). '+result.ignored.length+' non-source items ignored.');}else{if(dirty()&&!confirm('Replace current workspace? Download unsaved changes first.'))return;load(result.files,result.snapshot.entry,result.snapshot.view,result.snapshot.overrides,result.snapshot.layoutState);if(result.ignored.length)note(`Opened DDN workspace; ${result.ignored.length} non-source files ignored.`);}mergeNext=false;}
function editDialog(title,fields,action){$('dialog-title').textContent=title;$('dialog-error').textContent='';$('dialog-fields').replaceChildren(...fields.map(f=>{const l=document.createElement('label');l.textContent=f.label;let input=f.options?document.createElement('select'):document.createElement('input');input.name=f.name;input.required=f.required!==false;if(f.options)input.append(...f.options.map(o=>new Option(o.label,o.value)));else input.value=f.value||'';l.append(input);return l;}));dialogAction=action;$('edit-dialog').showModal();}
$('edit-form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();try{const values=Object.fromEntries(new FormData($('edit-form')));flush();dialogAction(values);$('edit-dialog').close();if(currentFile&&Object.hasOwn(ws.getFiles(),currentFile))showFile(currentFile);refreshModel();note('Source updated. Undo restores the previous source.');}catch(err){$('dialog-error').textContent=(err.code||'ERROR')+': '+err.message;}});
function guided(action){flush();action();showFile(currentFile);refreshModel();updateHistory();note('Source edit applied; dependent views use the same changed definition.');}
$('apply').onclick=()=>guard(()=>{flush();const old=entry+'#'+view;entriesUI(view);if(!diagram||old!==entry+'#'+view)mount();else{diagram.ready=diagram.redraw();diagram.ready.catch(()=>{});}refreshModel();});
$('source').addEventListener('input',()=>{bufferDirty=true;$('dirty').textContent='Unapplied edits';cursor();clearTimeout(timer);if($('live-apply').checked)timer=setTimeout(()=>guard(flush),450);});
$('source').addEventListener('click',cursor);$('source').addEventListener('keyup',cursor);
$('source').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();guard(saveFile);}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();$('apply').click();}if(e.key==='Tab'){e.preventDefault();const t=e.target,start=t.selectionStart,end=t.selectionEnd;t.setRangeText('    ',start,end,'end');t.dispatchEvent(new Event('input'));}});
$('file-search').oninput=filesUI;
$('entry').onchange=()=>guard(()=>{flush();entry=$('entry').value;entriesUI();showFile(entry);mount();});$('view').onchange=()=>guard(()=>{flush();view=$('view').value;mount();});$('outline').onchange=()=>guard(()=>{selection($('outline').value);});
$('load-example').onclick=()=>guard(()=>loadExample(Number($('example-select').value)));
$('new-project').onclick=()=>{if(!dirty()||confirm('Replace current workspace? Download unsaved changes first.'))load({'main.ddn':fresh},'main.ddn','overview');};
$('open-files').onclick=()=>{mergeNext=false;$('file-input').value='';$('file-input').click();};$('merge-files').onclick=()=>{mergeNext=true;$('file-input').value='';$('file-input').click();};$('open-folder').onclick=()=>{mergeNext=false;$('folder-input').value='';$('folder-input').click();};
$('file-input').onchange=e=>guard(()=>openFiles(e.target.files));$('folder-input').onchange=e=>guard(()=>openFiles(e.target.files,true));
$('download-file').onclick=()=>guard(saveFile);$('download-project').onclick=()=>guard(()=>saveWorkspace(true));$('download-json').onclick=()=>guard(()=>saveWorkspace(false));
$('undo').onclick=()=>guard(()=>{flush();ws.undo();entriesUI(view);if(!Object.hasOwn(ws.getFiles(),currentFile))currentFile=Object.keys(ws.getFiles())[0];showFile(currentFile);mount(diagram?.options||{});});$('redo').onclick=()=>guard(()=>{flush();ws.redo();entriesUI(view);if(!Object.hasOwn(ws.getFiles(),currentFile))currentFile=Object.keys(ws.getFiles())[0];showFile(currentFile);mount(diagram?.options||{});});
$('new-file').onclick=()=>editDialog('New source file',[{name:'path',label:'Workspace-relative filename',value:'data/new.ddn'}],v=>{A.pathChecked(v.path);if(Object.hasOwn(ws.getFiles(),v.path))throw new Error('File exists.');const m='user.'+v.path.replace(/[^A-Za-z0-9]/g,'_');ws.updateFiles({[v.path]:`ddn "0.5";\nmodule "${m}";\n\ndata model {\n    // Add definitions here.\n}\n`});showFile(v.path);});
$('rename-file').onclick=()=>editDialog('Rename / move source file',[{name:'path',label:'New workspace-relative path',value:currentFile}],v=>{const old=currentFile;ws.renameFile(old,v.path);if(entry===old)entry=v.path;currentFile=v.path;entriesUI(view);showFile(v.path);mount(diagram?.options||{});});
$('delete-file').onclick=()=>guard(()=>{flush();if(!confirm('Delete '+currentFile+' from this in-memory workspace?'))return;ws.removeFile(currentFile);currentFile=Object.keys(ws.getFiles())[0]||'';entriesUI(view);if(currentFile)showFile(currentFile);else $('source').value='';mount();});
$('find-next').onclick=()=>{const q=prompt('Find text',search);if(q===null||!q)return;search=q;const t=$('source'),at=t.value.indexOf(q,t.selectionEnd),pos=at>=0?at:t.value.indexOf(q);if(pos<0){note('Text not found.');return;}t.focus();t.setSelectionRange(pos,pos+q.length);cursor();};
$('replace-text').onclick=()=>{const q=prompt('Exact text to replace',search);if(!q)return;const to=prompt('Replace with','');if(to===null)return;const matches=$('source').value.split(q).length-1;if(!matches){note('No matches.');return;}if(!confirm('Replace all '+matches+' exact text occurrences in the current file? This is text editing, not identifier refactoring.'))return;$('source').value=$('source').value.split(q).join(to);$('source').dispatchEvent(new Event('input'));};
$('goto-line').onclick=()=>{const n=Number(prompt('Line number','1'));if(!Number.isInteger(n)||n<1)return;const t=$('source'),lines=t.value.split('\n'),at=lines.slice(0,n-1).reduce((x,l)=>x+l.length+1,0);t.focus();t.setSelectionRange(Math.min(at,t.value.length),Math.min(at,t.value.length));t.scrollTop=Math.max(0,(n-4)*20);cursor();};
$('preview-only').onclick=()=>{document.body.classList.toggle('preview-expanded');$('preview-only').textContent=document.body.classList.contains('preview-expanded')?'Show source panels':'Expand preview';};
$('set-label').onclick=()=>guard(()=>guided(()=>A.authoring.setLabel(ws,entry,view,selected,$('label-value').value)));
$('set-kind').onclick=()=>guard(()=>guided(()=>A.authoring.setProperty(ws,entry,view,selected,'kind',$('kind-value').value)));
$('pin').onclick=()=>guard(()=>guided(()=>A.authoring.pin(ws,entry,view,selected,Number($('position-x').value),Number($('position-y').value))));
$('unpin').onclick=()=>guard(()=>guided(()=>A.authoring.unpin(ws,entry,view,selected)));
$('hide').onclick=()=>guard(()=>guided(()=>A.authoring.hide(ws,entry,view,selected)));
$('go-source').onclick=()=>guard(()=>{const s=A.authoring.sourceOf(ws,entry,view,selected);showFile(s.file,s);});
$('delete-definition').onclick=()=>guard(()=>{if(confirm('Delete this semantic definition? Referenced definitions are blocked; use Hide for appearance-only removal.'))guided(()=>A.authoring.deleteDefinition(ws,entry,view,selected));});
$('add-element').onclick=()=>editDialog('Add an element',[{name:'id',label:'Stable identifier',value:'new_element'},{name:'name',label:'Display name',value:'New element'},{name:'kind',label:'Object kind',options:A.kinds.map(k=>({value:k.id,label:k.label}))}],v=>guided(()=>A.authoring.addElement(ws,entry,view,v)));
$('add-field').onclick=()=>editDialog('Add a field',[{name:'id',label:'Stable field identifier',value:'new_field'},{name:'name',label:'Display name',required:false}],v=>guided(()=>A.authoring.addField(ws,entry,view,selected,v)));
$('add-relation').onclick=()=>guard(()=>{flush();refreshModel();if(!lastModel)throw new Error('Fix source errors first.');const endpoints=lastModel.elements.flatMap(n=>[{value:n.id,label:n.name},...n.fields.map(f=>({value:f.id,label:n.name+'.'+f.name}))]);editDialog('Add a relationship',[{name:'id',label:'Stable relation identifier',value:'new_relation'},{name:'name',label:'Displayed description',value:'Related to'},{name:'from',label:'Source endpoint',options:endpoints},{name:'to',label:'Destination endpoint',options:endpoints},{name:'kind',label:'Registered relationship kind',options:A.relations.map(k=>({value:k.id,label:k.label}))}],v=>guided(()=>A.authoring.addRelation(ws,entry,view,v)));});
function attachDrag(){const canvas=diagram?.shadowRoot?.querySelector('.canvas');if(!canvas||canvas.dataset.studioDrag)return;canvas.dataset.studioDrag='true';let drag=null;
 canvas.addEventListener('pointerdown',e=>{if(!$('drag-mode').checked||e.button!==0)return;const el=e.target.closest('.ddn-node[data-id]'),g=diagram.result?.scene.nodes.find(n=>n.id===el?.dataset.id),drawing=el?.closest('svg')?.querySelector('g[id$="drawing"]');if(!el||!g||!drawing||diagram.capabilities.sequence||diagram.capabilities.graphControls===false)return;const inv=drawing.getScreenCTM()?.inverse();if(!inv)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(inv);drag={el,g,id:g.id,inv,start:point,dx:0,dy:0};canvas.setPointerCapture(e.pointerId);e.preventDefault();});
 canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(drag.inv);drag.dx=p.x-drag.start.x;drag.dy=p.y-drag.start.y;drag.el.setAttribute('transform',`translate(${drag.dx} ${drag.dy})`);});
 const finish=(e,cancel=false)=>{if(!drag)return;const d=drag;drag=null;d.el.removeAttribute('transform');if(!cancel&&Math.hypot(d.dx,d.dy)>2)guard(()=>{flush();A.authoring.pin(ws,entry,view,d.id,d.g.x+d.dx,d.g.y+d.dy);showFile(currentFile);selected=d.id;note('Pinned occurrence in source. Other unpinned elements may reflow; Undo restores the previous source.');});};canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,true));
}
window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue='';}});
const entries=all.catalogue.entries||[];$('example-select').replaceChildren(...entries.map((e,i)=>new Option(e.title+' · '+(e.collection||e.entry.split('/')[0]),String(i))));
const params=new URLSearchParams(location.search),desired=entries.findIndex(e=>e.entry===params.get('entry')&&(!params.get('view')||e.view===params.get('view')));
if(desired>=0){const e=entries[desired];$('example-select').value=String(desired);load(closure(e.entry),e.entry,e.view);}else load({'main.ddn':fresh},'main.ddn','overview');
// Documented test/integration inspection surface; no code evaluation API.
window.DDNStudio={get workspace(){return ws;},get diagram(){return diagram;},get currentFile(){return currentFile;},get entry(){return entry;},get view(){return view;},load,flush,snapshot,openFiles,selection};
})();
