#!/usr/bin/env node
/* SPDX-License-Identifier: GPL-2.0-or-later. Build the single-file unified DDN
 * tool (B1-027), mirroring tools/build-viewer.js. Inlines
 * notation/dist/ddn.global.min.js + the example corpus data
 * (notation/studio/assets/workspaces.js, same payload the studio pages carry)
 * + notation/tool/src/{tool.css,tool.js} into notation/tool/src/template.html
 * and writes notation/tool/ddn-tool.html.
 * Deterministic: fixed inputs, no timestamps. Run after npm run build:sdk. */
'use strict';
const fs = require('node:fs'), path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');

const RUNTIME_SRC = 'notation/dist/ddn.global.min.js';
const runtime = read(RUNTIME_SRC)
  // The source map ships in dist; the URL comment is meaningless once inlined.
  .replace(/\n\/\/# sourceMappingURL=\S+\n$/, '\n');
const data = read('notation/studio/assets/workspaces.js');
const css = read('notation/tool/src/tool.css');
/* B1-071: tool.js is decomposed into UMD modules under notation/tool/src/;
 * they are inlined ahead of tool.js (each attaches to globalThis; tool.js
 * picks them up via its __req helper's host fallback). */
const TOOL_MODULES = ['ddna-keel', 'options', 'params', 'pagefit', 'presentation', 'files', 'document-loader', 'tiles', 'export', 'bridge', 'inspector', 'forms', 'sheets', 'mermaid-import', 'ddna-trace', 'ddna-declarative', 'ddna-engine', 'rule-editor'];
const js = TOOL_MODULES.map(m => read('notation/tool/src/' + m + '.js')).join('\n') + '\n' + read('notation/tool/src/tool.js');
const template = read('notation/tool/src/template.html');
/* B1-043 (D6): the render worker is a Blob-URL worker built from a source
 * string the page already carries — the minified runtime plus the worker
 * bootstrap — so the tool stays one self-contained file and never fetches a
 * worker script (which file:// pages and strict CSP contexts could not). */
const WORKER_BOOT_SRC = 'notation/tool/src/worker.js';
const workerSource = runtime.trimEnd() + '\n;\n' + read(WORKER_BOOT_SRC).trimEnd() + '\n';
// DDN brand (B1-020, renamed B1-067): inline logo + data-URI favicon keep the single file self-contained.
const brandSvg = read('assets/brand/ddn.svg').replace(/<\?xml[^?]*\?>\s*/, '').replace(/<!--[\s\S]*?-->\s*/, '').trim();
const brandFavicon = 'data:image/svg+xml;base64,' + Buffer.from(brandSvg).toString('base64');

/* DDN 0.8 (ch. 57 §D2): "New document" templates are content files under
 * notation/tool/templates/ — ordinary .ddn sources, keyed by template id
 * (the view kind where one applies). Inlined verbatim so the picker works
 * from file:// with zero fetches. */
const TEMPLATES_DIR = 'notation/tool/templates';
const templates = {};
for (const f of fs.readdirSync(path.join(root, TEMPLATES_DIR)).filter(f => f.endsWith('.ddn')).sort())
  templates[f.replace(/\.ddn$/, '')] = read(TEMPLATES_DIR + '/' + f);
const templatesJs = '/* Inlined from ' + TEMPLATES_DIR + '/ (*.ddn content files) by tools/build-tool.js — "New document" template sources (chapter 57 §D2). */\nglobalThis.DDN_TOOL_TEMPLATES=' + JSON.stringify(templates, null, 0) + ';';

/* Designer phase 4: the property descriptor registry driving the generated
 * forms (Inspector Details tab, source-backed drawer groups). Generated from
 * the standard registry + runtime extension contracts by
 * designer/contracts/build-form-descriptors.mjs — freshness-gated by
 * notation/tests/tool.js. */
const FORMS_SRC = 'designer/contracts/form-descriptors.json';
const formsJs = '/* Inlined from ' + FORMS_SRC + ' (generated by designer/contracts/build-form-descriptors.mjs) — descriptor-driven form registry (designer spec 05). */\nglobalThis.DDN_FORM_DESCRIPTORS=' + read(FORMS_SRC).trim() + ';';

for (const [name, src] of [['runtime', runtime], ['workspaces data', data], ['tool.js', js], ['worker source', workerSource], ['templates', templatesJs], ['form descriptors', formsJs]]) {
  if (src.includes('</script')) throw new Error(name + ' contains </script; inlining would break the page');
}
const out = template
  .replace('{{TOOL_CSS}}', () => css.trimEnd())
  .replace('{{BRAND_FAVICON}}', () => brandFavicon)
  .replace('{{BRAND_LOGO}}', () => brandSvg)
  .replace('{{DDN_RUNTIME}}', () => '/* Inlined from ' + RUNTIME_SRC + ' (minified production build; readable ddn.global.js ships alongside in notation/dist). */\n' + runtime.trimEnd())
  .replace('{{DDN_WORKER_SOURCE}}', () => '/* B1-043: Blob-URL render worker source — ' + RUNTIME_SRC + ' + ' + WORKER_BOOT_SRC + ', as one string literal. */\nglobalThis.DDN_WORKER_SOURCE=' + JSON.stringify(workerSource) + ';')
  .replace('{{DDN_DATA}}', () => '/* Inlined from notation/studio/assets/workspaces.js — the example corpus the studio pages carry. */\n' + data.trimEnd())
  .replace('{{DDN_TEMPLATES}}', () => templatesJs)
  .replace('{{DDN_FORMS}}', () => formsJs)
  .replace('{{TOOL_JS}}', () => js.trimEnd());
if (out.includes('{{')) throw new Error('template placeholder left unsubstituted');

const target = path.join(root, 'notation/tool/ddn-tool.html');
fs.writeFileSync(target, out);
console.log('notation/tool/ddn-tool.html:', out.length, 'bytes');
