/* SPDX-License-Identifier: GPL-2.0-or-later. One public distribution built from the active 0.3 sources. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),read=n=>fs.readFileSync(path.join(root,n),'utf8');
const version=require('../package.json').version;
const parts=['ddn-defaults','ddn-quality-data','ddn-projection-data','ddn-profile-quality','ddn-profiles','ddn-contracts','ddn-core','ddn-sketch','ddn-patterns','ddn-palette','ddn-text','ddn-shapes','ddn-layout','ddn-export','ddn-placement','ddn-render','ddn-interaction','ddn-quality-render','ddn-projections','ddn-engine'].map(n=>'notation/runtime/'+n+'.js');
const registry=JSON.parse(read('standard/registry/catalogue.json')),glyphs=read('standard/registry/glyph-library.svg').match(/<defs>([\s\S]*?)<\/defs>/)[1];
const header=`/*! DDN ${version} · GPL-2.0-or-later · unified public runtime (no old compatibility renderer) */\n(function(host){'use strict';\nif(host.DDNLive?.VERSION===${JSON.stringify(version)}){if(typeof module==='object'&&module.exports)module.exports=host.DDNLive;return;}\nif(host.DDNLive)throw new Error('A different DDNLive runtime is already loaded. Load exactly one version.');\nconst backend=(function(){const globalThis={};const module=undefined;globalThis.DDNProfileCatalogue=${JSON.stringify(JSON.parse(read('standard/registry/profiles/catalogue.json'))).replace(/</g,'\\u003c')};\n`;
const body=header+parts.map(read).join('\n')+`\nreturn{DDN:globalThis.DDN,Defaults:globalThis.DDNDefaults,Render:globalThis.DDNRender,Interaction:globalThis.DDNInteraction,Placement:globalThis.DDNPlacement,Text:globalThis.DDNText,Export:globalThis.DDNExport,Projections:globalThis.DDNProjections,Engine:globalThis.DDNEngine};})();\nconst assets=`+JSON.stringify({registry,glyphs}).replace(/</g,'\\u003c')+';\n'+['api','io','authoring','component'].map(n=>read('notation/studio/src/'+n+'.js')).join('\n')+`\nconst api=makeLiveAPI(backend,assets);installIO(api);installAuthoring(api,backend,assets);host.DDNLive=api;installComponents(api,host);if(typeof module==='object'&&module.exports)module.exports=api;\n})(typeof globalThis!=='undefined'?globalThis:this);\n`;
fs.mkdirSync(path.join(root,'notation/dist'),{recursive:true});fs.writeFileSync(path.join(root,'notation/dist/ddn.global.js'),body);fs.copyFileSync(path.join(root,'notation/studio/src/public.d.ts'),path.join(root,'notation/dist/ddn.d.ts'));fs.copyFileSync(path.join(root,'notation/studio/src/public.d.ts'),path.join(root,'notation/dist/ddn.d.mts'));
fs.copyFileSync(path.join(root,'notation/studio/src/ddn.css'),path.join(root,'notation/dist/ddn.css'));
fs.writeFileSync(path.join(root,'notation/dist/ddn.mjs'),`import './ddn.global.js';\nconst ddn=globalThis.DDNLive;\nexport const {VERSION,runtime,createWorkspace,registerWorkspace,mount,fromSnapshot,authoring,io,parse,profileCatalogue}=ddn;\nexport default ddn;\n`);
fs.mkdirSync(path.join(root,'release/validation'),{recursive:true});fs.writeFileSync(path.join(root,'release/validation/sdk-build.json'),JSON.stringify({version,sourceFiles:parts,sha256:crypto.createHash('sha256').update(body).digest('hex'),bytes:Buffer.byteLength(body),gzipBytes:zlib.gzipSync(body).length,core:require('../notation/runtime/ddn-core.js').VERSION,oldCompatibilityRendererIncluded:false,fontFilesIncluded:false},null,2)+'\n');
console.log('SDK',version,Buffer.byteLength(body),'bytes');
