#!/usr/bin/env node
/* SPDX-License-Identifier: GPL-2.0-or-later. B1-019: SDK distribution build.
 * Generates the runtime asset modules (tools/build-assets.js), bundles the
 * ESM sources with Rollup (tools/rollup.config.mjs) into the five public
 * bundles × three formats (IIFE .js, minified .min.js + source map, ESM .mjs),
 * copies types/CSS, and writes the freshness manifest + generated dist README.
 * Output overrides for the freshness test: DDN_SDK_OUT, DDN_SDK_MANIFEST. */
'use strict';
const fs = require('node:fs'), path = require('node:path'), zlib = require('node:zlib'), crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const version = require('../package.json').version;

require('./build-assets.js'); // writes notation/runtime/assets/*.js (deterministic)

const out = process.env.DDN_SDK_OUT || path.join(root, 'notation/dist');
const manifestPath = process.env.DDN_SDK_MANIFEST || path.join(root, 'release/validation/sdk-build.json');
const stem = n => (n === 'global' ? 'ddn.global' : 'ddn-' + n);
const sha = s => crypto.createHash('sha256').update(s).digest('hex');
const entryFiles = n => fs.readdirSync(path.join(root, 'notation/runtime')).filter(f => f.endsWith('.js'));

(async () => {
  const { rollup } = require('rollup');
  const { default: configs, MEMBERS, BUNDLES } = await import('./rollup.config.mjs');
  fs.mkdirSync(out, { recursive: true });
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  const bytes = {};
  for (const config of configs) {
    const bundle = await rollup(config);
    const outputs = Array.isArray(config.output) ? config.output : [config.output];
    for (const o of outputs) {
      const { output } = await bundle.write(o);
      for (const chunk of output) bytes[path.basename(chunk.fileName)] = chunk.type === 'chunk' ? Buffer.byteLength(chunk.code) : Buffer.byteLength(chunk.source ?? '');
    }
    await bundle.close();
  }
  // Types + CSS copies (unchanged from the concatenation build).
  for (const n of [...Object.keys(BUNDLES).filter(n => n !== 'global'), '']) {
    const base = n ? stem(n) : 'ddn';
    for (const ext of ['d.ts', 'd.mts']) fs.copyFileSync(path.join(root, 'notation/studio/src/public.d.ts'), path.join(out, base + '.' + ext));
  }
  fs.copyFileSync(path.join(root, 'notation/studio/src/ddn.css'), path.join(out, 'ddn.css'));

  const read = f => fs.readFileSync(path.join(out, f));
  const bundles = {};
  for (const n of Object.keys(BUNDLES)) {
    const s = stem(n);
    const mjs = n === 'global' ? 'ddn.mjs' : s + '.mjs';
    const formats = {};
    for (const f of [s + '.js', mjs, s + '.min.js', s + '.min.js.map']) {
      const content = read(f);
      formats[f === mjs ? 'mjs' : f.slice(s.length + 1)] = { bytes: content.length, sha256: sha(content), gzipBytes: zlib.gzipSync(content).length };
    }
    bundles[n] = {
      bytes: formats['js'].bytes, sha256: formats['js'].sha256,
      files: (MEMBERS[n] || Object.entries(MEMBERS).filter(([k]) => k !== 'geo').flatMap(([, v]) => v)).map(f => 'notation/runtime/' + f + '.js'),
      formats,
    };
  }
  const coreVersion = require('../notation/runtime/ddn-core.js').default.VERSION;
  const full = read('ddn.global.js');
  fs.writeFileSync(manifestPath, JSON.stringify({
    version,
    builder: 'rollup@' + JSON.parse(fs.readFileSync(path.join(root, 'node_modules/rollup/package.json'), 'utf8')).version + ' (@rollup/plugin-terser@' + JSON.parse(fs.readFileSync(path.join(root, 'node_modules/@rollup/plugin-terser/package.json'), 'utf8')).version + ')',
    sourceFiles: bundles.global.files,
    sha256: sha(full), bytes: full.length, gzipBytes: zlib.gzipSync(full).length,
    core: coreVersion,
    oldCompatibilityRendererIncluded: false,
    fontFilesIncluded: false,
    bundles,
  }, null, 2) + '\n');

  /* dist/README.md is generated — never hand-edit. */
  const row = (n, blurb, needs) => {
    const s = stem(n), f = bundles[n].formats;
    return `| \`${s}.js\` / \`.mjs\` / \`.min.js\` | ${blurb} | ${needs} | ${f.js.bytes} | ${f.mjs.bytes} | ${f['min.js'].bytes} | ${f['min.js'].gzipBytes} |`;
  };
  const readme = `# DDN runtime bundles (dist/)

Generated by \`tools/build-sdk.js\` (Rollup) at build time — do not hand-edit. Version ${version}.
The runtime has **zero runtime dependencies**; the build toolchain (Rollup +
terser) is a pinned devDependency and never ships inside these bundles.

| Bundle | Contains | Requires loaded first | .js bytes | .mjs bytes | .min.js bytes | .min.js gzip |
|---|---|---|---|---|---|
${row('core', BUNDLES.core.blurb, '—')}
${row('graph', BUNDLES.graph.blurb, 'ddn-core.js')}
${row('quality', BUNDLES.quality.blurb, 'ddn-core.js + ddn-graph.js')}
${row('projections', BUNDLES.projections.blurb, 'ddn-core.js + ddn-graph.js')}
${row('geo', BUNDLES.geo.blurb, 'ddn-core.js + ddn-graph.js')}
${row('global', 'All-in-one: every bundle above except the optional ddn-geo, plus the Studio web component. Unchanged name and behavior; this is what the test suites and standalone pages embed.', '—')}

Every bundle ships three formats: a readable browser IIFE (\`.js\`, publishes
the documented globals \`DDNLive\`, \`DDNRender\`, \`DDNProjections\`,
\`DDNQualityRender\`, \`DDNGeo\`), a minified IIFE with source map (\`.min.js\` +
\`.min.js.map\`), and a real ES module (\`.mjs\`). Types: \`d.ts\`/\`d.mts\`
copies per bundle. \`ddn.css\` carries the default mark styles (page CSS wins
over script-inlined presentation).

## ES modules and tree-shaking

The \`.mjs\` bundles are Rollup-built ES modules with named exports for both the
live API (\`VERSION\`, \`createWorkspace\`, \`parse\`, …, plus default) and the
internal namespaces (\`DDN\`, \`DDNRender\`, \`DDNProjections\`, …). Non-core
\`.mjs\` files import their prerequisite bundles first, so a single \`import\`
of \`./ddn-graph.mjs\` (etc.) is self-sufficient. The package carries a
\`sideEffects\` annotation covering the IIFE entry points, so downstream
bundlers can tree-shake the \`.mjs\` builds when you import just what you need.

## npm subpaths

\`@ddn/notation\` resolves to \`ddn.global.js\`/\`ddn.mjs\`; the subpaths \`./core\`,
\`./graph\`, \`./projections\`, \`./quality\`, \`./geo\` resolve to the matching modular bundles
(\`require\` → \`.js\`, \`import\` → \`.mjs\`, types → \`.d.ts\`/\`.d.mts\`). In ESM the
modules load prerequisites automatically; in CommonJS \`require('@ddn/notation/core')\`
before any non-core subpath (same realm, same-version module stacking is a no-op).

## Load order

\`ddn-core.js\` first, then \`ddn-graph.js\`, then \`ddn-quality.js\`,
\`ddn-projections.js\` and the optional \`ddn-geo.js\` in any order. Each non-core bundle throws immediately if its
prerequisite is missing; loading the same bundle twice is a no-op; mixing versions
throws the single-version guard. Do not mix \`ddn.global.js\` with the modular bundles
on one page — load either the all-in-one or the modules.

The engine is a registry: \`DDNEngine.registerProjectionRenderer(name, fn)\`. The graph
renderer registers as \`graph\` inside ddn-graph.js; chart/matrix/panels/timeline/table/
sequence/timing/chen register inside ddn-projections.js; fishbone/decision register
inside ddn-quality.js; the optional geographic module registers \`geo\` inside
ddn-geo.js with \`optional: true\`. Rendering or planning an unregistered kind throws coded error
\`DDN-E010\` naming the kind and the bundle that provides it — with one owner-directed
exception: a geo view rendered without ddn-geo.js produces an inline SVG placeholder
("Map view requires ddn-geo.js") plus the coded \`DDN-E010\` diagnostic on the
diagnostics channel (never silent); the rest of the page renders. The fishbone and decision
renderers compose the page through ddn-projections.js, so those two kinds need both
ddn-quality.js and ddn-projections.js at render time.

## Typical combinations

- Check/validate/export only, or headless tooling: \`ddn-core.js\`.
- Classic diagrams (ERD, flow, C4, state, BPMN…): \`ddn-core.js\` + \`ddn-graph.js\`.
- Charts/matrices/timelines: add \`ddn-projections.js\`.
- Quality charts, decision tables, fishbone: add \`ddn-quality.js\` (and
  \`ddn-projections.js\` for page composition).
- Geographic maps: add \`ddn-geo.js\` (optional; missing module degrades to a
  visible placeholder, never silently).
- Everything except geo, one script tag: \`ddn.global.js\`.

## Data refresh

Every core build (ddn-core.js, ddn.global.js) exposes \`ws.replaceData(name, records)\` on the
workspace object: it rewrites only the named data block's record lines with the canonical
authoring serializer and returns \`{revision, diagnostics}\` — coded errors \`DDN-E002\`
(unknown/ambiguous block) and \`DDN-E011\` (field-shape mismatch) leave the source untouched.
Hosts then call \`renderSync\`/\`mount\` again; a same-values refresh re-renders every view
byte-identical. See \`examples/embed/data-refresh.html\`.
`;
  fs.writeFileSync(path.join(out, 'README.md'), readme);
  console.log('SDK', version, bytes['ddn.global.js'], 'bytes;',
    Object.keys(BUNDLES).map(n => stem(n) + '.js=' + bytes[stem(n) + '.js'] + ' .min.js=' + bytes[stem(n) + '.min.js'] + ' .mjs=' + bytes[(n === 'global' ? 'ddn' : stem(n)) + '.mjs']).join(' '));
})().catch(e => { console.error(e); process.exitCode = 1; });
