#!/usr/bin/env node
/* SPDX-License-Identifier: GPL-2.0-or-later. B1-019 (D1): generate the small
 * ESM asset modules under notation/runtime/assets/ from the canonical
 * standard/registry sources. Deterministic; committed; freshness-checked by
 * notation/tests/dist-freshness.js. Run via npm --prefix notation run build:sdk. */
'use strict';
const fs = require('node:fs'), path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = n => fs.readFileSync(path.join(root, n), 'utf8');
const json = v => JSON.stringify(v).replace(/</g, '\\u003c');
const outDir = process.env.DDN_ASSETS_OUT || path.join(root, 'notation/runtime/assets');
fs.mkdirSync(outDir, { recursive: true });
const banner = '/* Generated by tools/build-assets.js from standard/registry/ — do not hand-edit. */\n';
const files = {
  'catalogue.js': banner + 'export default ' + json(JSON.parse(read('standard/registry/catalogue.json'))) + ';\n',
  'profiles-catalogue.js': banner + 'export default ' + json(JSON.parse(read('standard/registry/profiles/catalogue.json'))) + ';\n',
  'glyphs.js': banner + 'export default ' + json(read('standard/registry/glyph-library.svg').match(/<defs>([\s\S]*?)<\/defs>/)[1]) + ';\n',
};
for (const [name, text] of Object.entries(files)) fs.writeFileSync(path.join(outDir, name), text);
console.log('assets:', Object.keys(files).map(n => n + '=' + Buffer.byteLength(files[n])).join(' '));
