#!/usr/bin/env node
/* SPDX-License-Identifier: GPL-2.0-or-later. B1-019 (D1): generate the small
 * ESM asset modules under notation/runtime/assets/ from the canonical
 * standard/registry sources. Deterministic; committed; freshness-checked by
 * notation/tests/dist-freshness.js. Run via npm --prefix notation run build:sdk. */
'use strict';
const fs = require('node:fs'), path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = n => fs.readFileSync(path.join(root, n), 'utf8');
const json = v => JSON.stringify(v).replace(/</g, '\\u003c');
const outDir = process.env.DDN_ASSETS_OUT || path.join(root, 'notation/runtime/assets');
fs.mkdirSync(outDir, { recursive: true });
const banner = '/* Generated by tools/build-assets.js from standard/registry/ — do not hand-edit. */\n';
const files = {
  'catalogue.js': banner + 'export default ' + json(JSON.parse(read('standard/registry/catalogue.json'))) + ';\n',
  'profiles-catalogue.js': banner + 'export default ' + json(JSON.parse(read('standard/registry/profiles/catalogue.json'))) + ';\n',
  'glyphs.js': banner + 'export default ' + json(read('standard/registry/glyph-library.svg').match(/<defs>([\s\S]*?)<\/defs>/)[1]) + ';\n',
  'units.js': banner + 'export default ' + json(JSON.parse(read('standard/registry/units.json'))) + ';\n',
};
/* Designer phase 2: palette grouping from the designer kind-ui-map contract
 * (keyword → palette_group, plus the ordered group list). The capability
 * derivation (ddn-capabilities.js) reads this asset; the contract JSON stays
 * the normative source. */
{
  const map = JSON.parse(read('designer/contracts/kind-ui-map.json'));
  const groups = [];
  const byKind = {};
  for (const k of map.kinds) {
    if (!groups.includes(k.palette_group)) groups.push(k.palette_group);
    byKind[k.kind] = k.palette_group;
  }
  files['kind-palette.js'] = banner + 'export default ' + json({ version: map.version, groups, byKind }) + ';\n';
}
/* B1-088: icon packs — one ddn-icon-pack@1 file per pack under
 * standard/registry/icon-packs/, ordered by index.json (default-binding
 * precedence). Aggregated here into the runtime asset shape; the packs and
 * their schema (standard/schemas/icon-pack.schema.json) are the normative
 * source. */
const packDir = path.join(root, 'standard/registry/icon-packs');
const packIndex = JSON.parse(read('standard/registry/icon-packs/index.json'));
const packLibraries = packIndex.packs.map(f => {
  const p = JSON.parse(read('standard/registry/icon-packs/' + f));
  const lib = { id: p.id, name: p.name, icons: p.icons };
  if (p.note) lib.note = p.note;
  lib.license = p.license; lib.attribution = p.attribution; lib.source = p.source;
  return lib;
});
files['icon-libraries.js'] = banner + 'export default ' + json({
  version: 'ddn-icon-libraries@1',
  status: 'Aggregated from standard/registry/icon-packs/ (ddn-icon-pack@1 files, ordered by index.json). Edit the packs, not this file. Vendor packs (Cisco/AWS/Azure/GCP) excluded pending licensing diligence.',
  libraries: packLibraries,
}) + ';\n';
for (const [name, text] of Object.entries(files)) fs.writeFileSync(path.join(outDir, name), text);
console.log('assets:', Object.keys(files).map(n => n + '=' + Buffer.byteLength(files[n])).join(' '));
