/* SPDX-License-Identifier: GPL-2.0-or-later. Composition layout and bounded SVG
 * document windows. Text and table model identities do not follow display order. */
import Text from './ddn-text.js';
import Fields from './ddn-field-layout.js';
import {namespace,publishNamespace} from './ddn-module-registry.js';
const DDN=namespace('DDN'),Documents=DDN.documents;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const cache=new Map();let retained=0;
function layout(doc,width,font,size,wrap,wrapCode=false){const key=JSON.stringify([doc.digest,doc.format,width,font,size,wrap,wrapCode,Text.engine,Text.revision()]);if(cache.has(key)&&typeof document==='undefined')return cache.get(key);const rows=Documents.parse(doc),lines=[];let y=0,max=0;
 for(const row of rows){const rowWrap=wrap&&(!row.code||wrapCode);const fs=row.level?size*(1.65-(row.level-1)*.12):size,step=fs*1.45,indent=(row.indent||0)*14;let runs=[],x=indent;const push=()=>{lines.push({y:y+fs,h:step,runs});max=Math.max(max,x);y+=step;runs=[];x=indent;};
  for(const r of row.runs){const f=r.code?'mono':font,w=r.bold?700:400,style=r.italic?{italic:true}:null,expanded=r.text.replace(/\t/g,'    ');const parts=rowWrap&&!row.code?expanded.split(/(\s+)/):[expanded];
   for(const part of parts){if(!part)continue;const m=Text.measure(part,fs,f,w,style).width;if(rowWrap&&x>indent&&x+m>width)push();
    if(rowWrap&&m>width-indent){for(const char of Text.graphemes(part)){const cw=Text.measure(char,fs,f,w,style).width;if(x>indent&&x+cw>width)push();const prev=runs.at(-1);if(prev&&prev.font===f&&prev.size===fs&&prev.weight===w&&prev.italic===!!style)prev.text+=char;else runs.push({text:char,x,size:fs,font:f,weight:w,italic:!!style});x+=cw;}}
    else{runs.push({text:part,x,size:fs,font:f,weight:w,italic:!!style});x+=m;}
   }
  }push();
 }
 const result={lines,width:max,height:y};if(typeof document==='undefined'){const bytes=JSON.stringify(result).length*2;cache.set(key,result);retained+=bytes;while(cache.size>64||retained>16000000){const k=cache.keys().next().value;retained-=JSON.stringify(cache.get(k)).length*2;cache.delete(k);}}return result;}
function measure(n,k,g,p){const c=n.properties.composition,sections=c.sections,s=g.scale,w=g.w,labelSpec=Text.mergeSpec(p.style?.text,n.properties?.text);const title=sections.includes('name')?Text.wrap(n.name,w-32*s,16*s,p.style.font,labelSpec?.weight??650,labelSpec):[];const header=(title.length?title.length*22*s+16*s:0)+(sections.includes('type')?28*s:0);let y=header||8*s;const oldTop=g.columnLayout?.top??g.headerH;const tableHeight=sections.includes('table')?Math.max(0,...g.fieldRows.map(r=>r.top+r.h-oldTop))+(g.fieldRows.length?8*s:0):0;
 let doc=n.properties.document;if(!doc&&n.properties.description)doc=Documents.document({format:'plain',text:n.properties.description});
 let note=null;if(doc&&sections.includes('notes')){const wrap=p.publication.note_mode==='full'||c.note_wrap==='on'||c.note_wrap==='auto'&&doc.format!=='code';const l=layout(doc,Math.max(40,w-46*s),p.style.font,12.5*s,wrap,p.publication.note_mode==='full'||c.note_wrap==='on');note={...l,format:doc.format,role:doc.role,digest:doc.digest,wrap,viewportWidth:w-44*s,viewportHeight:p.publication.note_mode==='full'?l.height:Math.min(l.height,c.note_height*s),full:p.publication.note_mode==='full',scale:s};}
 let rows=[];let columns=null;for(const block of c.order){if(block==='table'&&tableHeight){const delta=y-oldTop;rows=g.fieldRows.map(r=>({...r,top:r.top+delta}));if(g.columnLayout)columns={...g.columnLayout,top:y};y+=tableHeight;}else if(block==='notes'&&note){note.top=y+6*s;note.left=14*s;y+=note.viewportHeight+30*s;}}
 return {...g,n,k,w,h:Math.max(y+12*s,48*s),headerH:header,titleLines:title,fieldRows:rows,fields:sections.includes('table')?g.fields:[],columnLayout:columns,noteLines:[],meaningLines:[],footer:[],composition:c,noteViewport:note};}
function windowSVG(note,offsetX=0,offsetY=0,ink=note.ink||'#203047'){const low=offsetY,high=offsetY+note.viewportHeight,lines=note.lines;let lo=0,hi=lines.length;while(lo<hi){const mid=(lo+hi)>>1;if(lines[mid].y<low-30)lo=mid+1;else hi=mid;}let out='';for(let i=lo;i<lines.length;i++){const row=lines[i];if(row.y-row.h>high)break;for(const r of row.runs)out+=`<text x="${r.x-offsetX}" y="${row.y-offsetY}" font-family="${esc(Text.FONTS[r.font]||r.font)}" font-size="${r.size}" font-weight="${r.weight}"${r.italic?' font-style="italic"':''} fill="${esc(ink)}" xml:space="preserve">${esc(r.text)}</text>`;}return out;}
function paint(g,p,t){const {n,k,x,y,w,h,scale:s,composition:c,noteViewport:note}=g,mono=p.style.theme==='neutral'||p.theme08==='mono_print',ink=mono?'#000000':t.ink||'#203047',fill=mono?'#FFFFFF':n.properties.fill||t.surface||'#fff',pen=n.properties.stroke||{},stroke=mono?ink:pen.color||k.colour||ink,dash=DDN.LINE_DASH_PATTERNS[pen.dash],labelSpec=Text.mergeSpec(p.style?.text,n.properties?.text);let out=`<g class="ddn-node ddn-composed ddn-kind-${esc(k.code.toLowerCase())}"${n.properties.opacity!==undefined?` opacity="${n.properties.opacity}"`:''} data-id="${esc(n.id)}" data-ddn-id="${esc(n.id)}" tabindex="0" role="group" aria-label="${esc(n.name)}"><title>${esc(n.name+' — '+k.name)}</title><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${6*s}" fill="${esc(fill)}" stroke="${esc(stroke)}" stroke-width="${pen.weight??1}"${dash?` stroke-dasharray="${esc(dash)}"`:''}/>`;let yy=y+22*s;
 for(const title of g.titleLines){out+=`<text x="${x+14*s}" y="${yy}" font-size="${16*s}" font-weight="${labelSpec?.weight??650}" fill="${esc(labelSpec?.color??ink)}"${Text.paintAttrs(labelSpec)}>${esc(title)}</text>`;yy+=22*s;}
 if(c.sections.includes('type')){out+=`<use href="#g-${esc(k.glyph)}" x="${x+14*s}" y="${yy-14*s}" width="${20*s}" height="${20*s}"/><text x="${x+40*s}" y="${yy+2*s}" font-size="${11*s}" fill="${esc(ink)}">${esc(k.name)}</text>`;}
 const txt=(xx,yy,value,size,weight)=>`<text x="${xx}" y="${yy}" font-size="${size}" font-weight="${weight}" fill="${esc(ink)}">${esc(value)}</text>`;
 if(g.columnLayout)out+=Fields.paint(g,txt,(x1,y1,x2,y2)=>`<path d="M${x1} ${y1}L${x2} ${y2}" stroke="${esc(ink)}"/>`);
 else for(const row of g.fieldRows){out+=`<g class="ddn-field" data-member="${esc(row.id)}">`;let yy=y+row.top+18*s;for(const line of row.labelLines){out+=txt(x+(14+row.depth*16)*s,yy,line,13.5*s,400);yy+=18*s;}for(const line of row.detailLines){out+=txt(x+(14+row.depth*16)*s,yy,line,11.5*s,400);yy+=16*s;}out+='</g>';}
 if(note){note.ink=ink;const id='note-'+Array.from(n.id,c=>c.codePointAt(0).toString(16)).join('-'),nx=x+note.left,ny=y+note.top;out+=`<g class="ddn-note-window" data-note-id="${esc(n.id)}" transform="translate(${nx} ${ny})" tabindex="0" role="group" aria-label="${esc(n.name+' text document')}"><defs><clipPath id="${id}"><rect width="${note.viewportWidth}" height="${note.viewportHeight}"/></clipPath></defs><rect width="${note.viewportWidth}" height="${note.viewportHeight}" fill="${esc(fill)}" stroke="#94a3b8"/><g clip-path="url(#${id})"><g class="ddn-note-content">${windowSVG(note,0,0,ink)}</g></g>`;
 const vertical=note.height>note.viewportHeight+.1,horizontal=note.width>note.viewportWidth+.1;
 for(const axis of ['vertical','horizontal'])if(axis==='vertical'?vertical:horizontal){const v=axis==='vertical',length=v?note.viewportHeight:note.viewportWidth,content=v?note.height:note.width,thumb=Math.max(16,length*length/content);out+=`<g class="ddn-note-scroll" data-axis="${axis}" tabindex="0" role="scrollbar" aria-label="${axis} document scroll" aria-orientation="${axis}" aria-valuemin="0" aria-valuemax="${Math.ceil(content-length)}" aria-valuenow="0"><rect class="ddn-note-track" x="${v?note.viewportWidth+2:0}" y="${v?0:note.viewportHeight+2}" width="${v?12:length}" height="${v?length:12}" fill="#e2e8f0"/><rect class="ddn-note-thumb" x="${v?note.viewportWidth+2:0}" y="${v?0:note.viewportHeight+2}" width="${v?12:thumb}" height="${v?thumb:12}" rx="4" fill="#64748b"/></g>`;}
 if(vertical||horizontal)out+='<title>Scrollable text viewport. Complete content remains in the model; use publication note_mode full for full-text output.</title>';out+='</g>';}
 return out+'</g>';}
const api={measure,paint,layout,windowSVG};publishNamespace('DDNContent',api);export default api;
